-- ============================================================
-- JobRadar Company Seed Data - Part 2
-- Additional ~500 companies (Greenhouse + SmartRecruiters)
-- ============================================================

USE job_radar;

-- ============================================================
-- STEP 1: INSERT COMPANIES
-- ============================================================

INSERT IGNORE INTO company (name, industry, active) VALUES

-- FinTech & Payments
('Razorpay X',              'FinTech',          1),
('Cashfree',                'FinTech',          1),
('Payu',                    'FinTech',          1),
('BillDesk',                'FinTech',          1),
('Juspay',                  'FinTech',          1),
('Setu',                    'FinTech',          1),
('Niyo',                    'FinTech',          1),
('Jupiter',                 'FinTech',          1),
('Fi Money',                'FinTech',          1),
('Slice',                   'FinTech',          1),
('KreditBee',               'FinTech',          1),
('MoneyTap',                'FinTech',          1),
('EarlySalary',             'FinTech',          1),
('Kissht',                  'FinTech',          1),
('Lendingkart',             'FinTech',          1),
('Capital Float',           'FinTech',          1),
('Indifi',                  'FinTech',          1),
('Progcap',                 'FinTech',          1),
('Freo',                    'FinTech',          1),
('Axio',                    'FinTech',          1),
('Open Financial',          'FinTech',          1),
('Zaggle',                  'FinTech',          1),
('Mswipe',                  'FinTech',          1),
('Ezetap',                  'FinTech',          1),
('Pine Labs',               'FinTech',          1),
('Innoviti',                'FinTech',          1),
('Plural',                  'FinTech',          1),
('Lyra Network',            'FinTech',          1),
('Worldline',               'FinTech',          1),
('Global Payments',         'FinTech',          1),
('Fiserv',                  'FinTech',          1),
('FIS',                     'FinTech',          1),
('Temenos',                 'FinTech',          1),
('Finastra',                'FinTech',          1),
('Mambu',                   'FinTech',          1),
('Thought Machine',         'FinTech',          1),
('10x Banking',             'FinTech',          1),
('Starling Bank',           'FinTech',          1),
('Monzo',                   'FinTech',          1),
('Bunq',                    'FinTech',          1),
('Qonto',                   'FinTech',          1),
('Paysafe',                 'FinTech',          1),
('Nuvei',                   'FinTech',          1),
('Payoneer',                'FinTech',          1),
('Remitly',                 'FinTech',          1),
('WorldRemit',              'FinTech',          1),
('TransferGo',              'FinTech',          1),
('Xe',                      'FinTech',          1),
('OFX',                     'FinTech',          1),
('Currencycloud',           'FinTech',          1),

-- SaaS / B2B
('Zoho',                    'SaaS',             1),
('Salesken',                'SaaS',             1),
('Exotel',                  'SaaS',             1),
('Knowlarity',              'SaaS',             1),
('Ozonetel',                'SaaS',             1),
('Talkdesk India',          'SaaS',             1),
('Ameyo',                   'SaaS',             1),
('Freshchat',               'SaaS',             1),
('Haptik',                  'SaaS',             1),
('Yellow.ai',               'SaaS',             1),
('Verloop',                 'SaaS',             1),
('Gupshup',                 'SaaS',             1),
('Kaleyra',                 'SaaS',             1),
('Route Mobile',            'SaaS',             1),
('Tanla Platforms',         'SaaS',             1),
('ValueFirst',              'SaaS',             1),
('Textlocal',               'SaaS',             1),
('MSG91',                   'SaaS',             1),
('Netcore Cloud',           'SaaS',             1),
('WebEngage',               'SaaS',             1),
('Wigzo',                   'SaaS',             1),
('iZooto',                  'SaaS',             1),
('VWO',                     'SaaS',             1),
('Wingify',                 'SaaS',             1),
('Unbxd',                   'SaaS',             1),
('Bizom',                   'SaaS',             1),
('Capillary Technologies',  'SaaS',             1),
('Vinculum',                'SaaS',             1),
('Increff',                 'SaaS',             1),
('Unicommerce',             'SaaS',             1),
('Anchanto',                'SaaS',             1),
('Shiprocket',              'Logistics',        1),
('Delhivery',               'Logistics',        1),
('Ecom Express',            'Logistics',        1),
('Xpressbees',              'Logistics',        1),
('Shadowfax',               'Logistics',        1),
('Rivigo',                  'Logistics',        1),
('BlackBuck',               'Logistics',        1),
('Locus',                   'Logistics',        1),
('FarEye',                  'Logistics',        1),
('Increff',                 'Logistics',        1),

-- Cloud & Infrastructure
('Nutanix',                 'Cloud',            1),
('VMware',                  'Cloud',            1),
('Citrix',                  'Cloud',            1),
('NetApp',                  'Cloud',            1),
('Pure Storage',            'Cloud',            1),
('Commvault',               'Cloud',            1),
('Veeam',                   'Cloud',            1),
('Zerto',                   'Cloud',            1),
('Rubrik',                  'Cloud',            1),
('Cohesity',                'Cloud',            1),
('Wasabi',                  'Cloud',            1),
('Backblaze',               'Cloud',            1),
('Cloudian',                'Cloud',            1),
('MinIO',                   'Cloud',            1),
('Storj',                   'Cloud',            1),
('Fastly',                  'Cloud',            1),
('Akamai',                  'Cloud',            1),
('Imperva',                 'Security',         1),
('F5 Networks',             'Networking',       1),
('Arista Networks',         'Networking',       1),
('Juniper Networks',        'Networking',       1),
('Palo Alto',               'Security',         1),
('Fortinet',                'Security',         1),
('Zscaler',                 'Security',         1),
('Netskope',                'Security',         1),
('Illumio',                 'Security',         1),
('ColorTokens',             'Security',         1),
('Sectigo',                 'Security',         1),
('DigiCert',                'Security',         1),
('Entrust',                 'Security',         1),

-- DevOps & Developer Tools
('GitLab',                  'DevOps',           1),
('Bitbucket',               'DevOps',           1),
('Travis CI',               'DevOps',           1),
('Jenkins',                 'DevOps',           1),
('Spinnaker',               'DevOps',           1),
('ArgoCD',                  'DevOps',           1),
('Tekton',                  'DevOps',           1),
('Codefresh',               'DevOps',           1),
('Semaphore',               'DevOps',           1),
('Buddy',                   'DevOps',           1),
('Render',                  'Cloud',            1),
('Railway',                 'Cloud',            1),
('Fly.io',                  'Cloud',            1),
('Netlify',                 'Cloud',            1),
('Heroku',                  'Cloud',            1),
('Platform.sh',             'Cloud',            1),
('Jelastic',                'Cloud',            1),
('Divio',                   'Cloud',            1),
('Northflank',              'Cloud',            1),
('Porter',                  'Cloud',            1),

-- AI / ML
('OpenAI',                  'AI',               1),
('Anthropic',               'AI',               1),
('Inflection AI',           'AI',               1),
('Adept AI',                'AI',               1),
('Character AI',            'AI',               1),
('Perplexity AI',           'AI',               1),
('Runway',                  'AI',               1),
('Midjourney',              'AI',               1),
('ElevenLabs',              'AI',               1),
('Synthesia',               'AI',               1),
('DeepMind',                'AI',               1),
('Wayve',                   'AI',               1),
('Tractable',               'AI',               1),
('Onfido',                  'AI',               1),
('Quantexa',                'AI',               1),
('Darktrace India',         'AI',               1),
('Fractal Analytics',       'AI',               1),
('Mu Sigma',                'AI',               1),
('Tiger Analytics',         'AI',               1),
('Latent View',             'AI',               1),
('Sigmoid',                 'AI',               1),
('Crayon Data',             'AI',               1),
('Tredence',                'AI',               1),
('Bridgei2i',               'AI',               1),
('Absolutdata',             'AI',               1),
('Manthan',                 'AI',               1),
('Heckyl',                  'AI',               1),
('SigTuple',                'AI',               1),
('Niramai',                 'AI',               1),
('Qure.ai',                 'AI',               1),
('Tricog',                  'AI',               1),
('Arya.ai',                 'AI',               1),
('Staqu',                   'AI',               1),
('Mad Street Den',          'AI',               1),
('Uncanny Vision',          'AI',               1),
('Stellapps',               'AI',               1),
('Cropin',                  'AI',               1),
('Intello',                 'AI',               1),
('Mihup',                   'AI',               1),
('Gnani.ai',                'AI',               1),
('CoRover',                 'AI',               1),

-- Ecommerce & Retail Tech
('Shopify',                 'Ecommerce',        1),
('BigCommerce',             'Ecommerce',        1),
('Magento',                 'Ecommerce',        1),
('WooCommerce',             'Ecommerce',        1),
('PrestaShop',              'Ecommerce',        1),
('Commercetools',           'Ecommerce',        1),
('Fabric',                  'Ecommerce',        1),
('Elastic Path',            'Ecommerce',        1),
('Aptos',                   'Ecommerce',        1),
('Manhattan Associates',    'Ecommerce',        1),
('Blue Yonder',             'Supply Chain',     1),
('Kinaxis',                 'Supply Chain',     1),
('o9 Solutions',            'Supply Chain',     1),
('Llamasoft',               'Supply Chain',     1),
('Anaplan',                 'Supply Chain',     1),
('Infor',                   'ERP',              1),
('QAD',                     'ERP',              1),
('Syspro',                  'ERP',              1),
('Acumatica',               'ERP',              1),
('Priority Software',       'ERP',              1),
('Tata CLiQ',               'Ecommerce',        1),
('Snapdeal',                'Ecommerce',        1),
('ShopClues',               'Ecommerce',        1),
('IndiaMART',               'Ecommerce',        1),
('TradeIndia',              'Ecommerce',        1),
('Udaan',                   'Ecommerce',        1),
('Jumbotail',               'Ecommerce',        1),
('Ninjacart',               'Ecommerce',        1),
('Waycool',                 'Ecommerce',        1),
('DeHaat',                  'AgriTech',         1),
('Agristar',                'AgriTech',         1),
('Bijak',                   'AgriTech',         1),
('Gramophone',              'AgriTech',         1),
('AgroStar',                'AgriTech',         1),
('Jai Kisan',               'AgriTech',         1),
('Samunnati',               'AgriTech',         1),
('Stellapps Technologies',  'AgriTech',         1),
('FarmLink',                'AgriTech',         1),
('Khetivyapar',             'AgriTech',         1),

-- Mobility & Transport
('Rapido',                  'Mobility',         1),
('Bounce',                  'Mobility',         1),
('Yulu',                    'Mobility',         1),
('Vogo',                    'Mobility',         1),
('Drivezy',                 'Mobility',         1),
('Revv',                    'Mobility',         1),
('Zoomcar',                 'Mobility',         1),
('MyTVS',                   'Mobility',         1),
('Spinny',                  'Mobility',         1),
('Cars24',                  'Mobility',         1),
('CarDekho',                'Mobility',         1),
('CarWale',                 'Mobility',         1),
('Droom',                   'Mobility',         1),
('Cardekho Group',          'Mobility',         1),
('OLX Autos',               'Mobility',         1),
('Instacar',                'Mobility',         1),
('Turno',                   'EV',               1),
('Euler Motors',            'EV',               1),
('Altigreen',               'EV',               1),
('Log9 Materials',          'EV',               1),
('Ultraviolette',           'EV',               1),
('Tork Motors',             'EV',               1),
('Bounce Infinity',         'EV',               1),
('Simple Energy',           'EV',               1),
('Oben Electric',           'EV',               1),
('Kabira Mobility',         'EV',               1),

-- Real Estate & PropTech
('NoBroker',                'PropTech',         1),
('Housing.com',             'PropTech',         1),
('MagicBricks',             'PropTech',         1),
('99acres',                 'PropTech',         1),
('Square Yards',            'PropTech',         1),
('Anarock',                 'PropTech',         1),
('PropTiger',               'PropTech',         1),
('Stanza Living',           'PropTech',         1),
('OYO',                     'Hospitality',      1),
('Treebo',                  'Hospitality',      1),
('FabHotels',               'Hospitality',      1),
('Zostel',                  'Hospitality',      1),
('Wakefit',                 'Ecommerce',        1),
('Pepperfry',               'Ecommerce',        1),
('Urban Ladder',            'Ecommerce',        1),
('Furlenco',                'Ecommerce',        1),
('RentoMojo',               'Ecommerce',        1),
('Rentomojo',               'Ecommerce',        1),

-- Insurance Tech
('Acko',                    'InsurTech',        1),
('Digit Insurance',         'InsurTech',        1),
('Policybazaar',            'InsurTech',        1),
('Coverfox',                'InsurTech',        1),
('Turtlemint',              'InsurTech',        1),
('RenewBuy',                'InsurTech',        1),
('Symbo',                   'InsurTech',        1),
('Riskcovry',               'InsurTech',        1),
('Bima',                    'InsurTech',        1),
('Loop Health',             'InsurTech',        1),
('Plum Benefits',           'InsurTech',        1),
('Nova Benefits',           'InsurTech',        1),
('Onsurity',                'InsurTech',        1),
('Navi Technologies',       'InsurTech',        1),
('Zuno General Insurance',  'InsurTech',        1),

-- Gaming & Entertainment
('Games24x7',               'Gaming',           1),
('WinZO',                   'Gaming',           1),
('MPL',                     'Gaming',           1),
('Nazara Technologies',     'Gaming',           1),
('Junglee Games',           'Gaming',           1),
('GamesKraft',              'Gaming',           1),
('Zupee',                   'Gaming',           1),
('Hike',                    'Gaming',           1),
('Rooter',                  'Gaming',           1),
('Loco',                    'Gaming',           1),
('Glance',                  'Media',            1),
('DailyHunt',               'Media',            1),
('InShorts',                'Media',            1),
('Josh',                    'Media',            1),
('Moj',                     'Media',            1),
('MX Player',               'Media',            1),
('Eros Now',                'Media',            1),
('ZEE5',                    'Media',            1),
('SonyLIV',                 'Media',            1),
('JioCinema',               'Media',            1),
('Hotstar',                 'Media',            1),
('Spotify India',           'Media',            1),
('Gaana',                   'Media',            1),
('JioSaavn',                'Media',            1),
('Wynk Music',              'Media',            1),
('Hungama',                 'Media',            1),

-- HR Tech & Staffing
('Naukri.com',              'HR Tech',          1),
('Monster India',           'HR Tech',          1),
('Shine.com',               'HR Tech',          1),
('Apna',                    'HR Tech',          1),
('WorkIndia',               'HR Tech',          1),
('Freshteam',               'HR Tech',          1),
('Keka',                    'HR Tech',          1),
('GreytHR',                 'HR Tech',          1),
('Zimyo',                   'HR Tech',          1),
('HRMantra',                'HR Tech',          1),
('sumHR',                   'HR Tech',          1),
('Zoho People',             'HR Tech',          1),
('Kredily',                 'HR Tech',          1),
('Qandle',                  'HR Tech',          1),
('factoHR',                 'HR Tech',          1),
('Pocket HRMS',             'HR Tech',          1),
('Spine HR',                'HR Tech',          1),
('Akrivia HCM',             'HR Tech',          1),
('Empxtrack',               'HR Tech',          1),
('HROne',                   'HR Tech',          1),

-- Global Tech Giants (not in part 1)
('SAP',                     'Enterprise',       1),
('Oracle',                  'Database',         1),
('IBM',                     'Technology',       1),
('Microsoft',               'Technology',       1),
('Google',                  'Technology',       1),
('Meta',                    'Technology',       1),
('Amazon',                  'Ecommerce',        1),
('Apple',                   'Technology',       1),
('Intel',                   'Semiconductors',   1),
('AMD',                     'Semiconductors',   1),
('Qualcomm',                'Semiconductors',   1),
('NVIDIA',                  'Semiconductors',   1),
('Broadcom',                'Semiconductors',   1),
('Texas Instruments',       'Semiconductors',   1),
('Microchip Technology',    'Semiconductors',   1),
('Marvell Technology',      'Semiconductors',   1),
('Synopsys',                'EDA',              1),
('Cadence',                 'EDA',              1),
('Mentor Graphics',         'EDA',              1),
('Ansys',                   'EDA',              1),
('Altair',                  'EDA',              1),
('PTC',                     'EDA',              1),
('Dassault Aviation',       'Aerospace',        1),
('Boeing',                  'Aerospace',        1),
('Airbus',                  'Aerospace',        1),
('Lockheed Martin',         'Defense',          1),
('Raytheon',                'Defense',          1),
('General Dynamics',        'Defense',          1),
('Northrop Grumman',        'Defense',          1),
('BAE Systems',             'Defense',          1),
('Leidos',                  'Defense',          1),
('SAIC',                    'Defense',          1),
('Booz Allen Hamilton',     'Consulting',       1),
('McKinsey',                'Consulting',       1),
('BCG',                     'Consulting',       1),
('Bain',                    'Consulting',       1),
('Oliver Wyman',            'Consulting',       1),
('Roland Berger',           'Consulting',       1),
('Kearney',                 'Consulting',       1),
('Strategy&',               'Consulting',       1),
('Cognizant',               'IT Services',      1),
('TCS',                     'IT Services',      1),
('Infosys BPM',             'BPO',              1),
('Wipro BPO',               'BPO',              1),
('Firstsource',             'BPO',              1),
('iEnergizer',              'BPO',              1),
('Intelenet',               'BPO',              1),
('Hinduja Global',          'BPO',              1),
('Aegis',                   'BPO',              1),
('Mphasis BPO',             'BPO',              1),

-- Global SaaS (not in part 1)
('ServiceNow',              'Enterprise',       1),
('Workday HR',              'HR Tech',          1),
('Verint',                  'Customer Success', 1),
('NICE Systems',            'Customer Success', 1),
('Medallia',                'Customer Success', 1),
('Qualtrics',               'Analytics',        1),
('Sprinklr',                'MarTech',          1),
('Hootsuite',               'MarTech',          1),
('Sprout Social',           'MarTech',          1),
('Buffer',                  'MarTech',          1),
('Later',                   'MarTech',          1),
('Loomly',                  'MarTech',          1),
('CoSchedule',              'MarTech',          1),
('Planable',                'MarTech',          1),
('Socialbakers',            'MarTech',          1),
('Bazaarvoice',             'MarTech',          1),
('Yotpo',                   'MarTech',          1),
('Trustpilot',              'MarTech',          1),
('G2',                      'MarTech',          1),
('Capterra',                'MarTech',          1),
('GetApp',                  'MarTech',          1),
('Software Advice',         'MarTech',          1),
('TechTarget',              'Media',            1),
('IDG',                     'Media',            1),
('Gartner',                 'Consulting',       1),
('Forrester',               'Consulting',       1),
('IDC',                     'Consulting',       1),
('Ovum',                    'Consulting',       1),
('451 Research',            'Consulting',       1),
('IHS Markit',              'Consulting',       1);

-- ============================================================
-- STEP 2: GREENHOUSE company_ats MAPPINGS (Part 2)
-- ============================================================

INSERT IGNORE INTO company_ats (company_id, ats_platform_id, ats_job_url, active) VALUES
((SELECT id FROM company WHERE name = 'Cashfree'),              1, 'https://boards.greenhouse.io/cashfree',              1),
((SELECT id FROM company WHERE name = 'Juspay'),                1, 'https://boards.greenhouse.io/juspay',                1),
((SELECT id FROM company WHERE name = 'Setu'),                  1, 'https://boards.greenhouse.io/setu',                  1),
((SELECT id FROM company WHERE name = 'Niyo'),                  1, 'https://boards.greenhouse.io/niyo',                  1),
((SELECT id FROM company WHERE name = 'Jupiter'),               1, 'https://boards.greenhouse.io/jupiter',               1),
((SELECT id FROM company WHERE name = 'Fi Money'),              1, 'https://boards.greenhouse.io/fi',                    1),
((SELECT id FROM company WHERE name = 'Slice'),                 1, 'https://boards.greenhouse.io/sliceit',               1),
((SELECT id FROM company WHERE name = 'KreditBee'),             1, 'https://boards.greenhouse.io/kreditbee',             1),
((SELECT id FROM company WHERE name = 'Lendingkart'),           1, 'https://boards.greenhouse.io/lendingkart',           1),
((SELECT id FROM company WHERE name = 'Capital Float'),         1, 'https://boards.greenhouse.io/capitalfloat',          1),
((SELECT id FROM company WHERE name = 'Pine Labs'),             1, 'https://boards.greenhouse.io/pinelabs',              1),
((SELECT id FROM company WHERE name = 'Worldline'),             1, 'https://boards.greenhouse.io/worldline',             1),
((SELECT id FROM company WHERE name = 'Global Payments'),       1, 'https://boards.greenhouse.io/globalpayments',        1),
((SELECT id FROM company WHERE name = 'Fiserv'),                1, 'https://boards.greenhouse.io/fiserv',                1),
((SELECT id FROM company WHERE name = 'Temenos'),               1, 'https://boards.greenhouse.io/temenos',               1),
((SELECT id FROM company WHERE name = 'Mambu'),                 1, 'https://boards.greenhouse.io/mambu',                 1),
((SELECT id FROM company WHERE name = 'Thought Machine'),       1, 'https://boards.greenhouse.io/thoughtmachine',        1),
((SELECT id FROM company WHERE name = 'Monzo'),                 1, 'https://boards.greenhouse.io/monzo',                 1),
((SELECT id FROM company WHERE name = 'Remitly'),               1, 'https://boards.greenhouse.io/remitly',               1),
((SELECT id FROM company WHERE name = 'Payoneer'),              1, 'https://boards.greenhouse.io/payoneer',              1),
((SELECT id FROM company WHERE name = 'Zoho'),                  1, 'https://boards.greenhouse.io/zoho',                  1),
((SELECT id FROM company WHERE name = 'Exotel'),                1, 'https://boards.greenhouse.io/exotel',                1),
((SELECT id FROM company WHERE name = 'Haptik'),                1, 'https://boards.greenhouse.io/haptik',                1),
((SELECT id FROM company WHERE name = 'Yellow.ai'),             1, 'https://boards.greenhouse.io/yellowai',              1),
((SELECT id FROM company WHERE name = 'Gupshup'),               1, 'https://boards.greenhouse.io/gupshup',               1),
((SELECT id FROM company WHERE name = 'Kaleyra'),               1, 'https://boards.greenhouse.io/kaleyra',               1),
((SELECT id FROM company WHERE name = 'Netcore Cloud'),         1, 'https://boards.greenhouse.io/netcorecloud',          1),
((SELECT id FROM company WHERE name = 'WebEngage'),             1, 'https://boards.greenhouse.io/webengage',             1),
((SELECT id FROM company WHERE name = 'VWO'),                   1, 'https://boards.greenhouse.io/vwo',                   1),
((SELECT id FROM company WHERE name = 'Capillary Technologies'),1, 'https://boards.greenhouse.io/capillary',             1),
((SELECT id FROM company WHERE name = 'Shiprocket'),            1, 'https://boards.greenhouse.io/shiprocket',            1),
((SELECT id FROM company WHERE name = 'Delhivery'),             1, 'https://boards.greenhouse.io/delhivery',             1),
((SELECT id FROM company WHERE name = 'BlackBuck'),             1, 'https://boards.greenhouse.io/blackbuck',             1),
((SELECT id FROM company WHERE name = 'Locus'),                 1, 'https://boards.greenhouse.io/locus',                 1),
((SELECT id FROM company WHERE name = 'FarEye'),                1, 'https://boards.greenhouse.io/fareye',                1),
((SELECT id FROM company WHERE name = 'Nutanix'),               1, 'https://boards.greenhouse.io/nutanix',               1),
((SELECT id FROM company WHERE name = 'Pure Storage'),          1, 'https://boards.greenhouse.io/purestorage',           1),
((SELECT id FROM company WHERE name = 'Rubrik'),                1, 'https://boards.greenhouse.io/rubrik',                1),
((SELECT id FROM company WHERE name = 'Cohesity'),              1, 'https://boards.greenhouse.io/cohesity',              1),
((SELECT id FROM company WHERE name = 'Fastly'),                1, 'https://boards.greenhouse.io/fastly',                1),
((SELECT id FROM company WHERE name = 'Akamai'),                1, 'https://boards.greenhouse.io/akamai',                1),
((SELECT id FROM company WHERE name = 'Zscaler'),               1, 'https://boards.greenhouse.io/zscaler',               1),
((SELECT id FROM company WHERE name = 'Netskope'),              1, 'https://boards.greenhouse.io/netskope',              1),
((SELECT id FROM company WHERE name = 'Illumio'),               1, 'https://boards.greenhouse.io/illumio',               1),
((SELECT id FROM company WHERE name = 'GitLab'),                1, 'https://boards.greenhouse.io/gitlab',                1),
((SELECT id FROM company WHERE name = 'Codefresh'),             1, 'https://boards.greenhouse.io/codefresh',             1),
((SELECT id FROM company WHERE name = 'Render'),                1, 'https://boards.greenhouse.io/render',                1),
((SELECT id FROM company WHERE name = 'Netlify'),               1, 'https://boards.greenhouse.io/netlify',               1),
((SELECT id FROM company WHERE name = 'OpenAI'),                1, 'https://boards.greenhouse.io/openai',                1),
((SELECT id FROM company WHERE name = 'Anthropic'),             1, 'https://boards.greenhouse.io/anthropic',             1),
((SELECT id FROM company WHERE name = 'Perplexity AI'),         1, 'https://boards.greenhouse.io/perplexity',            1),
((SELECT id FROM company WHERE name = 'Runway'),                1, 'https://boards.greenhouse.io/runwayml',              1),
((SELECT id FROM company WHERE name = 'ElevenLabs'),            1, 'https://boards.greenhouse.io/elevenlabs',            1),
((SELECT id FROM company WHERE name = 'Synthesia'),             1, 'https://boards.greenhouse.io/synthesia',             1),
((SELECT id FROM company WHERE name = 'Onfido'),                1, 'https://boards.greenhouse.io/onfido',                1),
((SELECT id FROM company WHERE name = 'Fractal Analytics'),     1, 'https://boards.greenhouse.io/fractalanalytics',      1),
((SELECT id FROM company WHERE name = 'Qure.ai'),               1, 'https://boards.greenhouse.io/qureai',                1),
((SELECT id FROM company WHERE name = 'Shopify'),               1, 'https://boards.greenhouse.io/shopify',               1),
((SELECT id FROM company WHERE name = 'BigCommerce'),           1, 'https://boards.greenhouse.io/bigcommerce',           1),
((SELECT id FROM company WHERE name = 'Commercetools'),         1, 'https://boards.greenhouse.io/commercetools',         1),
((SELECT id FROM company WHERE name = 'Manhattan Associates'),  1, 'https://boards.greenhouse.io/manhattanassociates',   1),
((SELECT id FROM company WHERE name = 'Blue Yonder'),           1, 'https://boards.greenhouse.io/blueyonder',            1),
((SELECT id FROM company WHERE name = 'Kinaxis'),               1, 'https://boards.greenhouse.io/kinaxis',               1),
((SELECT id FROM company WHERE name = 'Anaplan'),               1, 'https://boards.greenhouse.io/anaplan',               1),
((SELECT id FROM company WHERE name = 'Infor'),                 1, 'https://boards.greenhouse.io/infor',                 1),
((SELECT id FROM company WHERE name = 'Cars24'),                1, 'https://boards.greenhouse.io/cars24',                1),
((SELECT id FROM company WHERE name = 'CarDekho'),              1, 'https://boards.greenhouse.io/cardekho',              1),
((SELECT id FROM company WHERE name = 'Spinny'),                1, 'https://boards.greenhouse.io/spinny',                1),
((SELECT id FROM company WHERE name = 'OYO'),                   1, 'https://boards.greenhouse.io/oyo',                   1),
((SELECT id FROM company WHERE name = 'NoBroker'),              1, 'https://boards.greenhouse.io/nobroker',              1),
((SELECT id FROM company WHERE name = 'Housing.com'),           1, 'https://boards.greenhouse.io/housingcom',            1),
((SELECT id FROM company WHERE name = 'Square Yards'),          1, 'https://boards.greenhouse.io/squareyards',           1),
((SELECT id FROM company WHERE name = 'Stanza Living'),         1, 'https://boards.greenhouse.io/stanzaliving',          1),
((SELECT id FROM company WHERE name = 'Acko'),                  1, 'https://boards.greenhouse.io/acko',                  1),
((SELECT id FROM company WHERE name = 'Digit Insurance'),       1, 'https://boards.greenhouse.io/digit',                 1),
((SELECT id FROM company WHERE name = 'Policybazaar'),          1, 'https://boards.greenhouse.io/policybazaar',          1),
((SELECT id FROM company WHERE name = 'Turtlemint'),            1, 'https://boards.greenhouse.io/turtlemint',            1),
((SELECT id FROM company WHERE name = 'Loop Health'),           1, 'https://boards.greenhouse.io/loophealth',            1),
((SELECT id FROM company WHERE name = 'Plum Benefits'),         1, 'https://boards.greenhouse.io/plumhq',                1),
((SELECT id FROM company WHERE name = 'Onsurity'),              1, 'https://boards.greenhouse.io/onsurity',              1),
((SELECT id FROM company WHERE name = 'Navi Technologies'),     1, 'https://boards.greenhouse.io/navi',                  1),
((SELECT id FROM company WHERE name = 'Games24x7'),             1, 'https://boards.greenhouse.io/games24x7',             1),
((SELECT id FROM company WHERE name = 'WinZO'),                 1, 'https://boards.greenhouse.io/winzo',                 1),
((SELECT id FROM company WHERE name = 'MPL'),                   1, 'https://boards.greenhouse.io/mpl',                   1),
((SELECT id FROM company WHERE name = 'Nazara Technologies'),   1, 'https://boards.greenhouse.io/nazara',                1),
((SELECT id FROM company WHERE name = 'Zupee'),                 1, 'https://boards.greenhouse.io/zupee',                 1),
((SELECT id FROM company WHERE name = 'Glance'),                1, 'https://boards.greenhouse.io/glance',                1),
((SELECT id FROM company WHERE name = 'DailyHunt'),             1, 'https://boards.greenhouse.io/dailyhunt',             1),
((SELECT id FROM company WHERE name = 'InShorts'),              1, 'https://boards.greenhouse.io/inshorts',              1),
((SELECT id FROM company WHERE name = 'Rapido'),                1, 'https://boards.greenhouse.io/rapido',                1),
((SELECT id FROM company WHERE name = 'Apna'),                  1, 'https://boards.greenhouse.io/apna',                  1),
((SELECT id FROM company WHERE name = 'Keka'),                  1, 'https://boards.greenhouse.io/keka',                  1),
((SELECT id FROM company WHERE name = 'Darwinbox'),             1, 'https://boards.greenhouse.io/darwinbox',             1),
((SELECT id FROM company WHERE name = 'SAP'),                   1, 'https://boards.greenhouse.io/sap',                   1),
((SELECT id FROM company WHERE name = 'ServiceNow'),            1, 'https://boards.greenhouse.io/servicenow',            1),
((SELECT id FROM company WHERE name = 'Medallia'),              1, 'https://boards.greenhouse.io/medallia',              1),
((SELECT id FROM company WHERE name = 'Qualtrics'),             1, 'https://boards.greenhouse.io/qualtrics',             1),
((SELECT id FROM company WHERE name = 'Sprinklr'),              1, 'https://boards.greenhouse.io/sprinklr',              1),
((SELECT id FROM company WHERE name = 'Hootsuite'),             1, 'https://boards.greenhouse.io/hootsuite',             1),
((SELECT id FROM company WHERE name = 'Sprout Social'),         1, 'https://boards.greenhouse.io/sproutsocial',          1),
((SELECT id FROM company WHERE name = 'Gartner'),               1, 'https://boards.greenhouse.io/gartner',               1),
((SELECT id FROM company WHERE name = 'Cognizant'),             1, 'https://boards.greenhouse.io/cognizant',             1),
((SELECT id FROM company WHERE name = 'TCS'),                   1, 'https://boards.greenhouse.io/tcs',                   1),
((SELECT id FROM company WHERE name = 'Synopsys'),              1, 'https://boards.greenhouse.io/synopsys',              1),
((SELECT id FROM company WHERE name = 'Cadence'),               1, 'https://boards.greenhouse.io/cadence',               1),
((SELECT id FROM company WHERE name = 'Ansys'),                 1, 'https://boards.greenhouse.io/ansys',                 1),
((SELECT id FROM company WHERE name = 'Qualcomm'),              1, 'https://boards.greenhouse.io/qualcomm',              1),
((SELECT id FROM company WHERE name = 'AMD'),                   1, 'https://boards.greenhouse.io/amd',                   1),
((SELECT id FROM company WHERE name = 'Broadcom'),              1, 'https://boards.greenhouse.io/broadcom',              1),
((SELECT id FROM company WHERE name = 'Marvell Technology'),    1, 'https://boards.greenhouse.io/marvell',               1),
((SELECT id FROM company WHERE name = 'Booz Allen Hamilton'),   1, 'https://boards.greenhouse.io/boozallenhamilton',     1),
((SELECT id FROM company WHERE name = 'Leidos'),                1, 'https://boards.greenhouse.io/leidos',                1),
((SELECT id FROM company WHERE name = 'Udaan'),                 1, 'https://boards.greenhouse.io/udaan',                 1),
((SELECT id FROM company WHERE name = 'Ninjacart'),             1, 'https://boards.greenhouse.io/ninjacart',             1),
((SELECT id FROM company WHERE name = 'AgroStar'),              1, 'https://boards.greenhouse.io/agrostar',              1),
((SELECT id FROM company WHERE name = 'Wakefit'),               1, 'https://boards.greenhouse.io/wakefit',               1),
((SELECT id FROM company WHERE name = 'Pepperfry'),             1, 'https://boards.greenhouse.io/pepperfry',             1),
((SELECT id FROM company WHERE name = 'Urban Ladder'),          1, 'https://boards.greenhouse.io/urbanladder',           1),
((SELECT id FROM company WHERE name = 'Furlenco'),              1, 'https://boards.greenhouse.io/furlenco',              1),
((SELECT id FROM company WHERE name = 'Tractable'),             1, 'https://boards.greenhouse.io/tractable',             1),
((SELECT id FROM company WHERE name = 'Quantexa'),              1, 'https://boards.greenhouse.io/quantexa',              1),
((SELECT id FROM company WHERE name = 'Wayve'),                 1, 'https://boards.greenhouse.io/wayve',                 1),
((SELECT id FROM company WHERE name = 'F5 Networks'),           1, 'https://boards.greenhouse.io/f5',                    1),
((SELECT id FROM company WHERE name = 'Arista Networks'),       1, 'https://boards.greenhouse.io/aristanetworks',        1),
((SELECT id FROM company WHERE name = 'Fortinet'),              1, 'https://boards.greenhouse.io/fortinet',              1);


-- ============================================================
-- SMARTRECRUITERS company_ats MAPPINGS (Part 2)
-- ============================================================

INSERT IGNORE INTO company_ats (company_id, ats_platform_id, ats_job_url, active) VALUES
((SELECT id FROM company WHERE name = 'Payu'),                  2, 'https://careers.smartrecruiters.com/PayU',                  1),
((SELECT id FROM company WHERE name = 'BillDesk'),              2, 'https://careers.smartrecruiters.com/BillDesk',              1),
((SELECT id FROM company WHERE name = 'Mswipe'),                2, 'https://careers.smartrecruiters.com/Mswipe',                1),
((SELECT id FROM company WHERE name = 'Pine Labs'),             2, 'https://careers.smartrecruiters.com/PineLabs',              1),
((SELECT id FROM company WHERE name = 'Worldline'),             2, 'https://careers.smartrecruiters.com/Worldline',             1),
((SELECT id FROM company WHERE name = 'FIS'),                   2, 'https://careers.smartrecruiters.com/FIS',                   1),
((SELECT id FROM company WHERE name = 'Finastra'),              2, 'https://careers.smartrecruiters.com/Finastra',              1),
((SELECT id FROM company WHERE name = 'Temenos'),               2, 'https://careers.smartrecruiters.com/Temenos',               1),
((SELECT id FROM company WHERE name = 'Paysafe'),               2, 'https://careers.smartrecruiters.com/Paysafe',               1),
((SELECT id FROM company WHERE name = 'Nuvei'),                 2, 'https://careers.smartrecruiters.com/Nuvei',                 1),
((SELECT id FROM company WHERE name = 'Exotel'),                2, 'https://careers.smartrecruiters.com/Exotel',                1),
((SELECT id FROM company WHERE name = 'Knowlarity'),            2, 'https://careers.smartrecruiters.com/Knowlarity',            1),
((SELECT id FROM company WHERE name = 'Route Mobile'),          2, 'https://careers.smartrecruiters.com/RouteMobile',           1),
((SELECT id FROM company WHERE name = 'Tanla Platforms'),       2, 'https://careers.smartrecruiters.com/TanlaPlatforms',        1),
((SELECT id FROM company WHERE name = 'Netcore Cloud'),         2, 'https://careers.smartrecruiters.com/NetcoreCloud',          1),
((SELECT id FROM company WHERE name = 'Capillary Technologies'),2, 'https://careers.smartrecruiters.com/CapillaryTechnologies', 1),
((SELECT id FROM company WHERE name = 'Vinculum'),              2, 'https://careers.smartrecruiters.com/Vinculum',              1),
((SELECT id FROM company WHERE name = 'Unicommerce'),           2, 'https://careers.smartrecruiters.com/Unicommerce',           1),
((SELECT id FROM company WHERE name = 'Shiprocket'),            2, 'https://careers.smartrecruiters.com/Shiprocket',            1),
((SELECT id FROM company WHERE name = 'Delhivery'),             2, 'https://careers.smartrecruiters.com/Delhivery',             1),
((SELECT id FROM company WHERE name = 'Ecom Express'),          2, 'https://careers.smartrecruiters.com/EcomExpress',           1),
((SELECT id FROM company WHERE name = 'Shadowfax'),             2, 'https://careers.smartrecruiters.com/Shadowfax',             1),
((SELECT id FROM company WHERE name = 'BlackBuck'),             2, 'https://careers.smartrecruiters.com/BlackBuck',             1),
((SELECT id FROM company WHERE name = 'VMware'),                2, 'https://careers.smartrecruiters.com/VMware',                1),
((SELECT id FROM company WHERE name = 'Citrix'),                2, 'https://careers.smartrecruiters.com/Citrix',                1),
((SELECT id FROM company WHERE name = 'NetApp'),                2, 'https://careers.smartrecruiters.com/NetApp',                1),
((SELECT id FROM company WHERE name = 'Commvault'),             2, 'https://careers.smartrecruiters.com/Commvault',             1),
((SELECT id FROM company WHERE name = 'Veeam'),                 2, 'https://careers.smartrecruiters.com/Veeam',                 1),
((SELECT id FROM company WHERE name = 'Imperva'),               2, 'https://careers.smartrecruiters.com/Imperva',               1),
((SELECT id FROM company WHERE name = 'Juniper Networks'),      2, 'https://careers.smartrecruiters.com/JuniperNetworks',       1),
((SELECT id FROM company WHERE name = 'Fortinet'),              2, 'https://careers.smartrecruiters.com/Fortinet',              1),
((SELECT id FROM company WHERE name = 'Zscaler'),               2, 'https://careers.smartrecruiters.com/Zscaler',               1),
((SELECT id FROM company WHERE name = 'Cognizant'),             2, 'https://careers.smartrecruiters.com/Cognizant',             1),
((SELECT id FROM company WHERE name = 'TCS'),                   2, 'https://careers.smartrecruiters.com/TataConsultancyServices',1),
((SELECT id FROM company WHERE name = 'IBM'),                   2, 'https://careers.smartrecruiters.com/IBM',                   1),
((SELECT id FROM company WHERE name = 'Oracle'),                2, 'https://careers.smartrecruiters.com/Oracle',                1),
((SELECT id FROM company WHERE name = 'SAP'),                   2, 'https://careers.smartrecruiters.com/SAP',                   1),
((SELECT id FROM company WHERE name = 'Infor'),                 2, 'https://careers.smartrecruiters.com/Infor',                 1),
((SELECT id FROM company WHERE name = 'ServiceNow'),            2, 'https://careers.smartrecruiters.com/ServiceNow',            1),
((SELECT id FROM company WHERE name = 'Gartner'),               2, 'https://careers.smartrecruiters.com/Gartner',               1),
((SELECT id FROM company WHERE name = 'Booz Allen Hamilton'),   2, 'https://careers.smartrecruiters.com/BoozAllenHamilton',     1),
((SELECT id FROM company WHERE name = 'McKinsey'),              2, 'https://careers.smartrecruiters.com/McKinsey',              1),
((SELECT id FROM company WHERE name = 'BCG'),                   2, 'https://careers.smartrecruiters.com/BCG',                   1),
((SELECT id FROM company WHERE name = 'Bain'),                  2, 'https://careers.smartrecruiters.com/BainAndCompany',        1),
((SELECT id FROM company WHERE name = 'Fractal Analytics'),     2, 'https://careers.smartrecruiters.com/FractalAnalytics',      1),
((SELECT id FROM company WHERE name = 'Mu Sigma'),              2, 'https://careers.smartrecruiters.com/MuSigma',               1),
((SELECT id FROM company WHERE name = 'Tredence'),              2, 'https://careers.smartrecruiters.com/Tredence',              1),
((SELECT id FROM company WHERE name = 'Firstsource'),           2, 'https://careers.smartrecruiters.com/Firstsource',           1),
((SELECT id FROM company WHERE name = 'Hinduja Global'),        2, 'https://careers.smartrecruiters.com/HindujaGlobalSolutions',1),
((SELECT id FROM company WHERE name = 'WNS'),                   2, 'https://careers.smartrecruiters.com/WNS',                   1),
((SELECT id FROM company WHERE name = 'EXL Service'),           2, 'https://careers.smartrecruiters.com/EXLService',            1),
((SELECT id FROM company WHERE name = 'Genpact'),               2, 'https://careers.smartrecruiters.com/Genpact',               1),
((SELECT id FROM company WHERE name = 'Concentrix'),            2, 'https://careers.smartrecruiters.com/Concentrix',            1),
((SELECT id FROM company WHERE name = 'Teleperformance'),       2, 'https://careers.smartrecruiters.com/Teleperformance',       1),
((SELECT id FROM company WHERE name = 'Ericsson'),              2, 'https://careers.smartrecruiters.com/Ericsson',              1),
((SELECT id FROM company WHERE name = 'Nokia'),                 2, 'https://careers.smartrecruiters.com/Nokia',                 1),
((SELECT id FROM company WHERE name = 'Amdocs'),                2, 'https://careers.smartrecruiters.com/Amdocs',                1),
((SELECT id FROM company WHERE name = 'NTT Data'),              2, 'https://careers.smartrecruiters.com/NTTData',               1),
((SELECT id FROM company WHERE name = 'Fujitsu'),               2, 'https://careers.smartrecruiters.com/Fujitsu',               1),
((SELECT id FROM company WHERE name = 'Hitachi'),               2, 'https://careers.smartrecruiters.com/Hitachi',               1),
((SELECT id FROM company WHERE name = 'Synopsys'),              2, 'https://careers.smartrecruiters.com/Synopsys',              1),
((SELECT id FROM company WHERE name = 'Cadence'),               2, 'https://careers.smartrecruiters.com/Cadence',               1),
((SELECT id FROM company WHERE name = 'Ansys'),                 2, 'https://careers.smartrecruiters.com/Ansys',                 1),
((SELECT id FROM company WHERE name = 'Qualcomm'),              2, 'https://careers.smartrecruiters.com/Qualcomm',              1),
((SELECT id FROM company WHERE name = 'Intel'),                 2, 'https://careers.smartrecruiters.com/Intel',                 1),
((SELECT id FROM company WHERE name = 'Broadcom'),              2, 'https://careers.smartrecruiters.com/Broadcom',              1),
((SELECT id FROM company WHERE name = 'Texas Instruments'),     2, 'https://careers.smartrecruiters.com/TexasInstruments',      1),
((SELECT id FROM company WHERE name = 'Honeywell'),             2, 'https://careers.smartrecruiters.com/Honeywell',             1),
((SELECT id FROM company WHERE name = 'ABB'),                   2, 'https://careers.smartrecruiters.com/ABB',                   1),
((SELECT id FROM company WHERE name = 'Siemens'),               2, 'https://careers.smartrecruiters.com/Siemens',               1),
((SELECT id FROM company WHERE name = 'BAE Systems'),           2, 'https://careers.smartrecruiters.com/BAESystemsInc',         1),
((SELECT id FROM company WHERE name = 'Raytheon'),              2, 'https://careers.smartrecruiters.com/Raytheon',              1),
((SELECT id FROM company WHERE name = 'Lockheed Martin'),       2, 'https://careers.smartrecruiters.com/LockheedMartin',        1),
((SELECT id FROM company WHERE name = 'Vodafone'),              2, 'https://careers.smartrecruiters.com/Vodafone',              1),
((SELECT id FROM company WHERE name = 'Deutsche Telekom'),      2, 'https://careers.smartrecruiters.com/DeutscheTelekom',       1),
((SELECT id FROM company WHERE name = 'OYO'),                   2, 'https://careers.smartrecruiters.com/OYO',                   1),
((SELECT id FROM company WHERE name = 'MagicBricks'),           2, 'https://careers.smartrecruiters.com/MagicBricks',           1),
((SELECT id FROM company WHERE name = 'Cars24'),                2, 'https://careers.smartrecruiters.com/CARS24',                1),
((SELECT id FROM company WHERE name = 'CarDekho'),              2, 'https://careers.smartrecruiters.com/CarDekho',              1),
((SELECT id FROM company WHERE name = 'Sprinklr'),              2, 'https://careers.smartrecruiters.com/Sprinklr',              1),
((SELECT id FROM company WHERE name = 'Hootsuite'),             2, 'https://careers.smartrecruiters.com/Hootsuite',             1),
((SELECT id FROM company WHERE name = 'Medallia'),              2, 'https://careers.smartrecruiters.com/Medallia',              1),
((SELECT id FROM company WHERE name = 'NICE Systems'),          2, 'https://careers.smartrecruiters.com/NICE',                  1),
((SELECT id FROM company WHERE name = 'Verint'),                2, 'https://careers.smartrecruiters.com/Verint',                1);

