-- ============================================================
-- JobRadar Company Seed Data
-- Schema: company (no career_page_url) + company_ats (holds URL)
-- ============================================================

USE job_radar;

-- ============================================================
-- ATS PLATFORM SEED (run first if not already seeded)
-- ============================================================

INSERT IGNORE INTO ats_platform (id, name, base_url_pattern, job_path_pattern, active) VALUES
(1, 'Greenhouse',      'https://boards.greenhouse.io/%s',        '/jobs', 1),
(2, 'SmartRecruiters', 'https://careers.smartrecruiters.com/%s', '',      1),
(3, 'Workday',         'https://%s.wd1.myworkdayjobs.com',       '/jobs', 1),
(4, 'Lever',           'https://jobs.lever.co/%s',               '',      1);

-- ============================================================
-- STEP 1: INSERT COMPANIES (name + industry only)
-- UNIQUE KEY on name — safe to re-run with INSERT IGNORE
-- ============================================================

INSERT IGNORE INTO company (name, industry, active) VALUES

-- India Product Companies
('Razorpay',              'FinTech',          1),
('Postman',               'API Platform',     1),
('BrowserStack',          'Testing',          1),
('Freshworks',            'SaaS',             1),
('Chargebee',             'Billing',          1),
('Druva',                 'Cloud',            1),
('Icertis',               'Enterprise',       1),
('Unacademy',             'EdTech',           1),
('Vedantu',               'EdTech',           1),
('CleverTap',             'MarTech',          1),
('MoEngage',              'MarTech',          1),
('Lenskart',              'Ecommerce',        1),
('Urban Company',         'Marketplace',      1),
('Nykaa',                 'Ecommerce',        1),
('Zetwerk',               'Manufacturing',    1),
('Darwinbox',             'HR Tech',          1),
('Leadsquared',           'CRM',              1),
('Kissflow',              'SaaS',             1),
('Sarvam AI',             'AI',               1),
('Krutrim',               'AI',               1),
('Swiggy',                'Marketplace',      1),
('Zomato',                'Marketplace',      1),
('Meesho',                'Ecommerce',        1),
('Flipkart',              'Ecommerce',        1),
('Ola',                   'Mobility',         1),
('CRED',                  'FinTech',          1),
('Groww',                 'FinTech',          1),
('Upstox',                'FinTech',          1),
('Dream11',               'Gaming',           1),
('ShareChat',             'Social',           1),
('InMobi',                'AdTech',           1),
('PhonePe',               'FinTech',          1),
('Paytm',                 'FinTech',          1),
('Ola Electric',          'EV',               1),
('Ather Energy',          'EV',               1),
('Practo',                'Health Tech',      1),
('PharmEasy',             'Health Tech',      1),
('1mg',                   'Health Tech',      1),
('HealthifyMe',           'Health Tech',      1),
('Pristyn Care',          'Health Tech',      1),
('Innovaccer',            'Health Tech',      1),
('scaler',                'EdTech',           1),
('upGrad',                'EdTech',           1),
('Great Learning',        'EdTech',           1),
('Emeritus',              'EdTech',           1),
('Simplilearn',           'EdTech',           1),
('Byju',                  'EdTech',           1),

-- Global Tech - Greenhouse
('Stripe',                'FinTech',          1),
('Datadog',               'Observability',    1),
('Atlassian',             'Collaboration',    1),
('Coinbase',              'Crypto',           1),
('Airbnb',                'Marketplace',      1),
('Pinterest',             'Social',           1),
('Reddit',                'Social',           1),
('GitHub',                'Developer Tools',  1),
('Okta',                  'Identity',         1),
('Elastic',               'Search',           1),
('MongoDB',               'Database',         1),
('Twilio',                'Communication',    1),
('HashiCorp',             'DevOps',           1),
('DigitalOcean',          'Cloud',            1),
('Confluent',             'Streaming',        1),
('Cloudflare',            'Networking',       1),
('HubSpot',               'CRM',              1),
('Notion',                'Productivity',     1),
('Rippling',              'HR Tech',          1),
('Deel',                  'HR Tech',          1),
('Figma',                 'Design',           1),
('Canva',                 'Design',           1),
('Airtable',              'Productivity',     1),
('Asana',                 'Productivity',     1),
('Vercel',                'Cloud',            1),
('Supabase',              'Database',         1),
('Retool',                'Developer Tools',  1),
('Segment',               'Data',             1),
('Amplitude',             'Analytics',        1),
('Mixpanel',              'Analytics',        1),
('Brex',                  'FinTech',          1),
('Ramp',                  'FinTech',          1),
('Plaid',                 'FinTech',          1),
('Robinhood',             'FinTech',          1),
('Chime',                 'FinTech',          1),
('Wise',                  'FinTech',          1),
('Revolut',               'FinTech',          1),
('Nubank',                'FinTech',          1),
('Klarna',                'FinTech',          1),
('Affirm',                'FinTech',          1),
('Checkout.com',          'FinTech',          1),
('Adyen',                 'FinTech',          1),
('Marqeta',               'FinTech',          1),
('Zuora',                 'Billing',          1),
('Paddle',                'Billing',          1),
('Intercom',              'Customer Success', 1),
('Zendesk',               'Customer Success', 1),
('Braze',                 'MarTech',          1),
('Iterable',              'MarTech',          1),
('Klaviyo',               'MarTech',          1),
('Contentful',            'CMS',              1),
('Algolia',               'Search',           1),
('LaunchDarkly',          'DevOps',           1),
('Harness',               'DevOps',           1),
('CircleCI',              'DevOps',           1),
('Sentry',                'Observability',    1),
('Grafana',               'Observability',    1),
('PagerDuty',             'Observability',    1),
('Pendo',                 'Analytics',        1),
('FullStory',             'Analytics',        1),
('Heap',                  'Analytics',        1),
('dbt Labs',              'Data',             1),
('Airbyte',               'Data',             1),
('Fivetran',              'Data',             1),
('Databricks',            'Data Platform',    1),
('Snowflake',             'Data Platform',    1),
('ThoughtSpot',           'Analytics',        1),
('CockroachDB',           'Database',         1),
('SingleStore',           'Database',         1),
('Redis',                 'Database',         1),
('Neo4j',                 'Database',         1),
('Yugabyte',              'Database',         1),
('Temporal',              'Developer Tools',  1),
('Kong',                  'API Platform',     1),
('Zapier',                'Integration',      1),
('Workato',               'Integration',      1),
('Cohere',                'AI',               1),
('Hugging Face',          'AI',               1),
('Scale AI',              'AI',               1),
('Weights & Biases',      'AI',               1),
('Labelbox',              'AI',               1),
('Pinecone',              'AI',               1),
('Weaviate',              'AI',               1),
('LangChain',             'AI',               1),
('Anyscale',              'AI',               1),
('Glean',                 'AI',               1),
('Moveworks',             'AI',               1),
('UiPath',                'Automation',       1),
('Automation Anywhere',   'Automation',       1),
('Appian',                'Automation',       1),
('Pega',                  'Automation',       1),
('Pipedrive',             'CRM',              1),
('Apollo',                'Sales',            1),
('Outreach',              'Sales',            1),
('Salesloft',             'Sales',            1),
('Gong',                  'Sales',            1),
('Clari',                 'Sales',            1),
('Seismic',               'Sales',            1),
('Mindtickle',            'Sales',            1),
('Lattice',               'HR Tech',          1),
('Personio',              'HR Tech',          1),
('HiBob',                 'HR Tech',          1),
('BambooHR',              'HR Tech',          1),
('Gusto',                 'HR Tech',          1),
('Greenhouse',            'HR Tech',          1),
('Lever',                 'HR Tech',          1),
('Ashby',                 'HR Tech',          1),
('Eightfold AI',          'HR Tech',          1),
('Remote',                'HR Tech',          1),
('Oyster',                'HR Tech',          1),
('Replit',                'Developer Tools',  1),
('Sourcegraph',           'Developer Tools',  1),
('JFrog',                 'Developer Tools',  1),
('Snyk',                  'Security',         1),
('Wiz',                   'Security',         1),
('CrowdStrike',           'Security',         1),
('SentinelOne',           'Security',         1),
('Palo Alto Networks',    'Security',         1),
('Lacework',              'Security',         1),
('Orca Security',         'Security',         1),
('Cyberark',              'Security',         1),
('Sailpoint',             'Security',         1),
('Tenable',               'Security',         1),
('Rapid7',                'Security',         1),
('Checkmarx',             'Security',         1),
('Veeva Systems',         'Life Sciences',    1),
('Benchling',             'Life Sciences',    1),
('Flatiron Health',       'Health Tech',      1),
('Duolingo',              'EdTech',           1),
('Coursera',              'EdTech',           1),
('Udemy',                 'EdTech',           1),
('Waymo',                 'Autonomous',       1),
('Cruise',                'Autonomous',       1),
('Rivian',                'EV',               1),
('Lucid Motors',          'EV',               1),
('SpaceX',                'Aerospace',        1),
('Palantir',              'Data',             1),
('Squarespace',           'Web Platform',     1),
('Webflow',               'Web Platform',     1),
('Calendly',              'Productivity',     1),
('ClickUp',               'Productivity',     1),
('Monday.com',            'Productivity',     1),
('Miro',                  'Collaboration',    1),
('Loom',                  'Communication',    1),
('Aircall',               'Communication',    1),
('Dialpad',               'Communication',    1),
('RingCentral',           'Communication',    1),
('Talkdesk',              'Customer Success', 1),
('Five9',                 'Customer Success', 1),
('Genesys',               'Customer Success', 1),

-- India IT Services - SmartRecruiters
('Infosys',               'IT Services',      1),
('Wipro',                 'IT Services',      1),
('HCL Technologies',      'IT Services',      1),
('Tech Mahindra',         'IT Services',      1),
('Mphasis',               'IT Services',      1),
('Hexaware',              'IT Services',      1),
('Persistent Systems',    'IT Services',      1),
('Zensar',                'IT Services',      1),
('KPIT Technologies',     'IT Services',      1),
('Cyient',                'IT Services',      1),
('Mastek',                'IT Services',      1),
('Tata Elxsi',            'IT Services',      1),
('L&T Technology Services','IT Services',     1),
('Birlasoft',             'IT Services',      1),

-- Global Enterprises - SmartRecruiters
('Bosch',                 'Manufacturing',    1),
('Visa',                  'FinTech',          1),
('IKEA',                  'Retail',           1),
('Volvo Group',           'Automotive',       1),
('Nokia',                 'Telecom',          1),
('Philips',               'Healthcare',       1),
('Publicis Groupe',       'Marketing',        1),
('Capgemini',             'Consulting',       1),
('Vestas',                'Energy',           1),
('LVMH',                  'Luxury',           1),
('Hilti',                 'Construction',     1),
('Takeda',                'Pharma',           1),
('Swarovski',             'Retail',           1),
('Axa',                   'Insurance',        1),
('TotalEnergies',         'Energy',           1),
('Veolia',                'Utilities',        1),
('Danone',                'Food',             1),
('Schneider Electric',    'Energy',           1),
('Air Liquide',           'Energy',           1),
('Siemens Mobility',      'Transport',        1),
('BNP Paribas',           'Banking',          1),
('Sodexo',                'Hospitality',      1),
('Dassault Systemes',     'Software',         1),
('Orange',                'Telecom',          1),
('Allianz',               'Insurance',        1),
('Thales',                'Defense',          1),
('Alstom',                'Transport',        1),
('Accor',                 'Hospitality',      1),
('Sanofi',                'Pharma',           1),
('Renault',               'Automotive',       1),
('Valeo',                 'Automotive',       1),
('Michelin',              'Automotive',       1),
('EDF',                   'Energy',           1),
('Engie',                 'Energy',           1),
('Heineken',              'Beverages',        1),
('Carlsberg',             'Beverages',        1),
('ABB',                   'Engineering',      1),
('Siemens',               'Engineering',      1),
('Honeywell',             'Engineering',      1),
('Ericsson',              'Telecom',          1),
('Deutsche Telekom',      'Telecom',          1),
('Vodafone',              'Telecom',          1),
('Teleperformance',       'BPO',              1),
('Concentrix',            'BPO',              1),
('WNS',                   'BPO',              1),
('EXL Service',           'BPO',              1),
('Genpact',               'BPO',              1),
('Amdocs',                'Telecom',          1),
('Fujitsu',               'IT Services',      1),
('NTT Data',              'IT Services',      1),
('Hitachi',               'Electronics',      1),
('NEC',                   'Electronics',      1),
('Tata Communications',   'Telecom',          1),
('Sterlite Tech',         'Telecom',          1);


-- ============================================================
-- STEP 2: INSERT company_ats ROWS
-- Uses subquery to resolve company_id by name
-- INSERT IGNORE avoids duplicates on re-run
-- ============================================================

-- GREENHOUSE mappings
INSERT IGNORE INTO company_ats (company_id, ats_platform_id, ats_job_url, active) VALUES
((SELECT id FROM company WHERE name = 'Razorpay'),           1, 'https://boards.greenhouse.io/razorpay',           1),
((SELECT id FROM company WHERE name = 'Postman'),            1, 'https://boards.greenhouse.io/postman',            1),
((SELECT id FROM company WHERE name = 'BrowserStack'),       1, 'https://boards.greenhouse.io/browserstack',       1),
((SELECT id FROM company WHERE name = 'Freshworks'),         1, 'https://boards.greenhouse.io/freshworks',         1),
((SELECT id FROM company WHERE name = 'Chargebee'),          1, 'https://boards.greenhouse.io/chargebee',          1),
((SELECT id FROM company WHERE name = 'Druva'),              1, 'https://boards.greenhouse.io/druva',              1),
((SELECT id FROM company WHERE name = 'Icertis'),            1, 'https://boards.greenhouse.io/icertis',            1),
((SELECT id FROM company WHERE name = 'Unacademy'),          1, 'https://boards.greenhouse.io/unacademy',          1),
((SELECT id FROM company WHERE name = 'Vedantu'),            1, 'https://boards.greenhouse.io/vedantu',            1),
((SELECT id FROM company WHERE name = 'CleverTap'),          1, 'https://boards.greenhouse.io/clevertap',          1),
((SELECT id FROM company WHERE name = 'MoEngage'),           1, 'https://boards.greenhouse.io/moengage',           1),
((SELECT id FROM company WHERE name = 'Lenskart'),           1, 'https://boards.greenhouse.io/lenskart',           1),
((SELECT id FROM company WHERE name = 'Urban Company'),      1, 'https://boards.greenhouse.io/urbancompany',       1),
((SELECT id FROM company WHERE name = 'Nykaa'),              1, 'https://boards.greenhouse.io/nykaa',              1),
((SELECT id FROM company WHERE name = 'Zetwerk'),            1, 'https://boards.greenhouse.io/zetwerk',            1),
((SELECT id FROM company WHERE name = 'Darwinbox'),          1, 'https://boards.greenhouse.io/darwinbox',          1),
((SELECT id FROM company WHERE name = 'Leadsquared'),        1, 'https://boards.greenhouse.io/leadsquared',        1),
((SELECT id FROM company WHERE name = 'Kissflow'),           1, 'https://boards.greenhouse.io/kissflow',           1),
((SELECT id FROM company WHERE name = 'Sarvam AI'),          1, 'https://boards.greenhouse.io/sarvamai',           1),
((SELECT id FROM company WHERE name = 'Krutrim'),            1, 'https://boards.greenhouse.io/krutrim',            1),
((SELECT id FROM company WHERE name = 'Swiggy'),             1, 'https://boards.greenhouse.io/swiggy',             1),
((SELECT id FROM company WHERE name = 'Zomato'),             1, 'https://boards.greenhouse.io/zomato',             1),
((SELECT id FROM company WHERE name = 'Meesho'),             1, 'https://boards.greenhouse.io/meesho',             1),
((SELECT id FROM company WHERE name = 'Flipkart'),           1, 'https://boards.greenhouse.io/flipkart',           1),
((SELECT id FROM company WHERE name = 'Ola'),                1, 'https://boards.greenhouse.io/olacabs',            1),
((SELECT id FROM company WHERE name = 'CRED'),               1, 'https://boards.greenhouse.io/cred',               1),
((SELECT id FROM company WHERE name = 'Groww'),              1, 'https://boards.greenhouse.io/groww',              1),
((SELECT id FROM company WHERE name = 'Upstox'),             1, 'https://boards.greenhouse.io/upstox',             1),
((SELECT id FROM company WHERE name = 'Dream11'),            1, 'https://boards.greenhouse.io/dream11',            1),
((SELECT id FROM company WHERE name = 'ShareChat'),          1, 'https://boards.greenhouse.io/sharechat',          1),
((SELECT id FROM company WHERE name = 'InMobi'),             1, 'https://boards.greenhouse.io/inmobi',             1),
((SELECT id FROM company WHERE name = 'PhonePe'),            1, 'https://boards.greenhouse.io/phonepe',            1),
((SELECT id FROM company WHERE name = 'Paytm'),              1, 'https://boards.greenhouse.io/paytm',              1),
((SELECT id FROM company WHERE name = 'Ola Electric'),       1, 'https://boards.greenhouse.io/olaelectric',        1),
((SELECT id FROM company WHERE name = 'Ather Energy'),       1, 'https://boards.greenhouse.io/atherenergy',        1),
((SELECT id FROM company WHERE name = 'Practo'),             1, 'https://boards.greenhouse.io/practo',             1),
((SELECT id FROM company WHERE name = 'PharmEasy'),          1, 'https://boards.greenhouse.io/pharmeasy',          1),
((SELECT id FROM company WHERE name = '1mg'),                1, 'https://boards.greenhouse.io/1mg',                1),
((SELECT id FROM company WHERE name = 'HealthifyMe'),        1, 'https://boards.greenhouse.io/healthifyme',        1),
((SELECT id FROM company WHERE name = 'Pristyn Care'),       1, 'https://boards.greenhouse.io/pristyncare',        1),
((SELECT id FROM company WHERE name = 'Innovaccer'),         1, 'https://boards.greenhouse.io/innovaccer',         1),
((SELECT id FROM company WHERE name = 'scaler'),             1, 'https://boards.greenhouse.io/scaler',             1),
((SELECT id FROM company WHERE name = 'upGrad'),             1, 'https://boards.greenhouse.io/upgrad',             1),
((SELECT id FROM company WHERE name = 'Great Learning'),     1, 'https://boards.greenhouse.io/greatlearning',      1),
((SELECT id FROM company WHERE name = 'Emeritus'),           1, 'https://boards.greenhouse.io/emeritus',           1),
((SELECT id FROM company WHERE name = 'Simplilearn'),        1, 'https://boards.greenhouse.io/simplilearn',        1),
((SELECT id FROM company WHERE name = 'Byju'),               1, 'https://boards.greenhouse.io/byju',               1),
((SELECT id FROM company WHERE name = 'Stripe'),             1, 'https://boards.greenhouse.io/stripe',             1),
((SELECT id FROM company WHERE name = 'Datadog'),            1, 'https://boards.greenhouse.io/datadog',            1),
((SELECT id FROM company WHERE name = 'Atlassian'),          1, 'https://boards.greenhouse.io/atlassian',          1),
((SELECT id FROM company WHERE name = 'Coinbase'),           1, 'https://boards.greenhouse.io/coinbase',           1),
((SELECT id FROM company WHERE name = 'Airbnb'),             1, 'https://boards.greenhouse.io/airbnb',             1),
((SELECT id FROM company WHERE name = 'Pinterest'),          1, 'https://boards.greenhouse.io/pinterest',          1),
((SELECT id FROM company WHERE name = 'Reddit'),             1, 'https://boards.greenhouse.io/reddit',             1),
((SELECT id FROM company WHERE name = 'GitHub'),             1, 'https://boards.greenhouse.io/github',             1),
((SELECT id FROM company WHERE name = 'Okta'),               1, 'https://boards.greenhouse.io/okta',               1),
((SELECT id FROM company WHERE name = 'Elastic'),            1, 'https://boards.greenhouse.io/elastic',            1),
((SELECT id FROM company WHERE name = 'MongoDB'),            1, 'https://boards.greenhouse.io/mongodb',            1),
((SELECT id FROM company WHERE name = 'Twilio'),             1, 'https://boards.greenhouse.io/twilio',             1),
((SELECT id FROM company WHERE name = 'HashiCorp'),          1, 'https://boards.greenhouse.io/hashicorp',          1),
((SELECT id FROM company WHERE name = 'DigitalOcean'),       1, 'https://boards.greenhouse.io/digitalocean',       1),
((SELECT id FROM company WHERE name = 'Confluent'),          1, 'https://boards.greenhouse.io/confluent',          1),
((SELECT id FROM company WHERE name = 'Cloudflare'),         1, 'https://boards.greenhouse.io/cloudflare',         1),
((SELECT id FROM company WHERE name = 'HubSpot'),            1, 'https://boards.greenhouse.io/hubspot',            1),
((SELECT id FROM company WHERE name = 'Notion'),             1, 'https://boards.greenhouse.io/notion',             1),
((SELECT id FROM company WHERE name = 'Rippling'),           1, 'https://boards.greenhouse.io/rippling',           1),
((SELECT id FROM company WHERE name = 'Deel'),               1, 'https://boards.greenhouse.io/deel',               1),
((SELECT id FROM company WHERE name = 'Figma'),              1, 'https://boards.greenhouse.io/figma',              1),
((SELECT id FROM company WHERE name = 'Canva'),              1, 'https://boards.greenhouse.io/canva',              1),
((SELECT id FROM company WHERE name = 'Airtable'),           1, 'https://boards.greenhouse.io/airtable',           1),
((SELECT id FROM company WHERE name = 'Asana'),              1, 'https://boards.greenhouse.io/asana',              1),
((SELECT id FROM company WHERE name = 'Vercel'),             1, 'https://boards.greenhouse.io/vercel',             1),
((SELECT id FROM company WHERE name = 'Supabase'),           1, 'https://boards.greenhouse.io/supabase',           1),
((SELECT id FROM company WHERE name = 'Retool'),             1, 'https://boards.greenhouse.io/retool',             1),
((SELECT id FROM company WHERE name = 'Segment'),            1, 'https://boards.greenhouse.io/segment',            1),
((SELECT id FROM company WHERE name = 'Amplitude'),          1, 'https://boards.greenhouse.io/amplitude',          1),
((SELECT id FROM company WHERE name = 'Mixpanel'),           1, 'https://boards.greenhouse.io/mixpanel',           1),
((SELECT id FROM company WHERE name = 'Brex'),               1, 'https://boards.greenhouse.io/brex',               1),
((SELECT id FROM company WHERE name = 'Ramp'),               1, 'https://boards.greenhouse.io/ramp',               1),
((SELECT id FROM company WHERE name = 'Plaid'),              1, 'https://boards.greenhouse.io/plaid',              1),
((SELECT id FROM company WHERE name = 'Robinhood'),          1, 'https://boards.greenhouse.io/robinhood',          1),
((SELECT id FROM company WHERE name = 'Chime'),              1, 'https://boards.greenhouse.io/chime',              1),
((SELECT id FROM company WHERE name = 'Wise'),               1, 'https://boards.greenhouse.io/wise',               1),
((SELECT id FROM company WHERE name = 'Revolut'),            1, 'https://boards.greenhouse.io/revolut',            1),
((SELECT id FROM company WHERE name = 'Nubank'),             1, 'https://boards.greenhouse.io/nubank',             1),
((SELECT id FROM company WHERE name = 'Klarna'),             1, 'https://boards.greenhouse.io/klarna',             1),
((SELECT id FROM company WHERE name = 'Affirm'),             1, 'https://boards.greenhouse.io/affirm',             1),
((SELECT id FROM company WHERE name = 'Checkout.com'),       1, 'https://boards.greenhouse.io/checkoutcom',        1),
((SELECT id FROM company WHERE name = 'Adyen'),              1, 'https://boards.greenhouse.io/adyen',              1),
((SELECT id FROM company WHERE name = 'Marqeta'),            1, 'https://boards.greenhouse.io/marqeta',            1),
((SELECT id FROM company WHERE name = 'Zuora'),              1, 'https://boards.greenhouse.io/zuora',              1),
((SELECT id FROM company WHERE name = 'Paddle'),             1, 'https://boards.greenhouse.io/paddle',             1),
((SELECT id FROM company WHERE name = 'Intercom'),           1, 'https://boards.greenhouse.io/intercom',           1),
((SELECT id FROM company WHERE name = 'Zendesk'),            1, 'https://boards.greenhouse.io/zendesk',            1),
((SELECT id FROM company WHERE name = 'Braze'),              1, 'https://boards.greenhouse.io/braze',              1),
((SELECT id FROM company WHERE name = 'Iterable'),           1, 'https://boards.greenhouse.io/iterable',           1),
((SELECT id FROM company WHERE name = 'Klaviyo'),            1, 'https://boards.greenhouse.io/klaviyo',            1),
((SELECT id FROM company WHERE name = 'Contentful'),         1, 'https://boards.greenhouse.io/contentful',         1),
((SELECT id FROM company WHERE name = 'Algolia'),            1, 'https://boards.greenhouse.io/algolia',            1),
((SELECT id FROM company WHERE name = 'LaunchDarkly'),       1, 'https://boards.greenhouse.io/launchdarkly',       1),
((SELECT id FROM company WHERE name = 'Harness'),            1, 'https://boards.greenhouse.io/harness',            1),
((SELECT id FROM company WHERE name = 'CircleCI'),           1, 'https://boards.greenhouse.io/circleci',           1),
((SELECT id FROM company WHERE name = 'Sentry'),             1, 'https://boards.greenhouse.io/sentry',             1),
((SELECT id FROM company WHERE name = 'Grafana'),            1, 'https://boards.greenhouse.io/grafana',            1),
((SELECT id FROM company WHERE name = 'PagerDuty'),          1, 'https://boards.greenhouse.io/pagerduty',          1),
((SELECT id FROM company WHERE name = 'Pendo'),              1, 'https://boards.greenhouse.io/pendo',              1),
((SELECT id FROM company WHERE name = 'FullStory'),          1, 'https://boards.greenhouse.io/fullstory',          1),
((SELECT id FROM company WHERE name = 'Heap'),               1, 'https://boards.greenhouse.io/heap',               1),
((SELECT id FROM company WHERE name = 'dbt Labs'),           1, 'https://boards.greenhouse.io/dbtlabs',            1),
((SELECT id FROM company WHERE name = 'Airbyte'),            1, 'https://boards.greenhouse.io/airbyte',            1),
((SELECT id FROM company WHERE name = 'Fivetran'),           1, 'https://boards.greenhouse.io/fivetran',           1),
((SELECT id FROM company WHERE name = 'Databricks'),         1, 'https://boards.greenhouse.io/databricks',         1),
((SELECT id FROM company WHERE name = 'Snowflake'),          1, 'https://boards.greenhouse.io/snowflake',          1),
((SELECT id FROM company WHERE name = 'ThoughtSpot'),        1, 'https://boards.greenhouse.io/thoughtspot',        1),
((SELECT id FROM company WHERE name = 'CockroachDB'),        1, 'https://boards.greenhouse.io/cockroachdb',        1),
((SELECT id FROM company WHERE name = 'SingleStore'),        1, 'https://boards.greenhouse.io/singlestore',        1),
((SELECT id FROM company WHERE name = 'Redis'),              1, 'https://boards.greenhouse.io/redislabs',          1),
((SELECT id FROM company WHERE name = 'Neo4j'),              1, 'https://boards.greenhouse.io/neo4j',              1),
((SELECT id FROM company WHERE name = 'Yugabyte'),           1, 'https://boards.greenhouse.io/yugabyte',           1),
((SELECT id FROM company WHERE name = 'Temporal'),           1, 'https://boards.greenhouse.io/temporal',           1),
((SELECT id FROM company WHERE name = 'Kong'),               1, 'https://boards.greenhouse.io/kong',               1),
((SELECT id FROM company WHERE name = 'Zapier'),             1, 'https://boards.greenhouse.io/zapier',             1),
((SELECT id FROM company WHERE name = 'Workato'),            1, 'https://boards.greenhouse.io/workato',            1),
((SELECT id FROM company WHERE name = 'Cohere'),             1, 'https://boards.greenhouse.io/cohere',             1),
((SELECT id FROM company WHERE name = 'Hugging Face'),       1, 'https://boards.greenhouse.io/huggingface',        1),
((SELECT id FROM company WHERE name = 'Scale AI'),           1, 'https://boards.greenhouse.io/scaleai',            1),
((SELECT id FROM company WHERE name = 'Weights & Biases'),   1, 'https://boards.greenhouse.io/wandb',              1),
((SELECT id FROM company WHERE name = 'Labelbox'),           1, 'https://boards.greenhouse.io/labelbox',           1),
((SELECT id FROM company WHERE name = 'Pinecone'),           1, 'https://boards.greenhouse.io/pinecone',           1),
((SELECT id FROM company WHERE name = 'Weaviate'),           1, 'https://boards.greenhouse.io/weaviate',           1),
((SELECT id FROM company WHERE name = 'LangChain'),          1, 'https://boards.greenhouse.io/langchain',          1),
((SELECT id FROM company WHERE name = 'Anyscale'),           1, 'https://boards.greenhouse.io/anyscale',           1),
((SELECT id FROM company WHERE name = 'Glean'),              1, 'https://boards.greenhouse.io/glean',              1),
((SELECT id FROM company WHERE name = 'Moveworks'),          1, 'https://boards.greenhouse.io/moveworks',          1),
((SELECT id FROM company WHERE name = 'UiPath'),             1, 'https://boards.greenhouse.io/uipath',             1),
((SELECT id FROM company WHERE name = 'Automation Anywhere'),1, 'https://boards.greenhouse.io/automationanywhere',  1),
((SELECT id FROM company WHERE name = 'Appian'),             1, 'https://boards.greenhouse.io/appian',             1),
((SELECT id FROM company WHERE name = 'Pega'),               1, 'https://boards.greenhouse.io/pega',               1),
((SELECT id FROM company WHERE name = 'Pipedrive'),          1, 'https://boards.greenhouse.io/pipedrive',          1),
((SELECT id FROM company WHERE name = 'Apollo'),             1, 'https://boards.greenhouse.io/apolloio',           1),
((SELECT id FROM company WHERE name = 'Outreach'),           1, 'https://boards.greenhouse.io/outreach',           1),
((SELECT id FROM company WHERE name = 'Salesloft'),          1, 'https://boards.greenhouse.io/salesloft',          1),
((SELECT id FROM company WHERE name = 'Gong'),               1, 'https://boards.greenhouse.io/gong',               1),
((SELECT id FROM company WHERE name = 'Clari'),              1, 'https://boards.greenhouse.io/clari',              1),
((SELECT id FROM company WHERE name = 'Seismic'),            1, 'https://boards.greenhouse.io/seismic',            1),
((SELECT id FROM company WHERE name = 'Mindtickle'),         1, 'https://boards.greenhouse.io/mindtickle',         1),
((SELECT id FROM company WHERE name = 'Lattice'),            1, 'https://boards.greenhouse.io/lattice',            1),
((SELECT id FROM company WHERE name = 'Personio'),           1, 'https://boards.greenhouse.io/personio',           1),
((SELECT id FROM company WHERE name = 'HiBob'),              1, 'https://boards.greenhouse.io/hibob',              1),
((SELECT id FROM company WHERE name = 'BambooHR'),           1, 'https://boards.greenhouse.io/bamboohr',           1),
((SELECT id FROM company WHERE name = 'Gusto'),              1, 'https://boards.greenhouse.io/gusto',              1),
((SELECT id FROM company WHERE name = 'Greenhouse'),         1, 'https://boards.greenhouse.io/greenhouse',         1),
((SELECT id FROM company WHERE name = 'Lever'),              1, 'https://boards.greenhouse.io/lever',              1),
((SELECT id FROM company WHERE name = 'Ashby'),              1, 'https://boards.greenhouse.io/ashby',              1),
((SELECT id FROM company WHERE name = 'Eightfold AI'),       1, 'https://boards.greenhouse.io/eightfoldai',        1),
((SELECT id FROM company WHERE name = 'Remote'),             1, 'https://boards.greenhouse.io/remote',             1),
((SELECT id FROM company WHERE name = 'Oyster'),             1, 'https://boards.greenhouse.io/oyster',             1),
((SELECT id FROM company WHERE name = 'Replit'),             1, 'https://boards.greenhouse.io/replit',             1),
((SELECT id FROM company WHERE name = 'Sourcegraph'),        1, 'https://boards.greenhouse.io/sourcegraph',        1),
((SELECT id FROM company WHERE name = 'JFrog'),              1, 'https://boards.greenhouse.io/jfrog',              1),
((SELECT id FROM company WHERE name = 'Snyk'),               1, 'https://boards.greenhouse.io/snyk',               1),
((SELECT id FROM company WHERE name = 'Wiz'),                1, 'https://boards.greenhouse.io/wiz',                1),
((SELECT id FROM company WHERE name = 'CrowdStrike'),        1, 'https://boards.greenhouse.io/crowdstrike',        1),
((SELECT id FROM company WHERE name = 'SentinelOne'),        1, 'https://boards.greenhouse.io/sentinelone',        1),
((SELECT id FROM company WHERE name = 'Palo Alto Networks'), 1, 'https://boards.greenhouse.io/paloaltonetworks',   1),
((SELECT id FROM company WHERE name = 'Lacework'),           1, 'https://boards.greenhouse.io/lacework',           1),
((SELECT id FROM company WHERE name = 'Orca Security'),      1, 'https://boards.greenhouse.io/orcasecurity',       1),
((SELECT id FROM company WHERE name = 'Cyberark'),           1, 'https://boards.greenhouse.io/cyberark',           1),
((SELECT id FROM company WHERE name = 'Sailpoint'),          1, 'https://boards.greenhouse.io/sailpoint',          1),
((SELECT id FROM company WHERE name = 'Tenable'),            1, 'https://boards.greenhouse.io/tenable',            1),
((SELECT id FROM company WHERE name = 'Rapid7'),             1, 'https://boards.greenhouse.io/rapid7',             1),
((SELECT id FROM company WHERE name = 'Checkmarx'),          1, 'https://boards.greenhouse.io/checkmarx',          1),
((SELECT id FROM company WHERE name = 'Veeva Systems'),      1, 'https://boards.greenhouse.io/veeva',              1),
((SELECT id FROM company WHERE name = 'Benchling'),          1, 'https://boards.greenhouse.io/benchling',          1),
((SELECT id FROM company WHERE name = 'Flatiron Health'),    1, 'https://boards.greenhouse.io/flatironhealth',     1),
((SELECT id FROM company WHERE name = 'Duolingo'),           1, 'https://boards.greenhouse.io/duolingo',           1),
((SELECT id FROM company WHERE name = 'Coursera'),           1, 'https://boards.greenhouse.io/coursera',           1),
((SELECT id FROM company WHERE name = 'Udemy'),              1, 'https://boards.greenhouse.io/udemy',              1),
((SELECT id FROM company WHERE name = 'Waymo'),              1, 'https://boards.greenhouse.io/waymo',              1),
((SELECT id FROM company WHERE name = 'Cruise'),             1, 'https://boards.greenhouse.io/cruise',             1),
((SELECT id FROM company WHERE name = 'Rivian'),             1, 'https://boards.greenhouse.io/rivian',             1),
((SELECT id FROM company WHERE name = 'Lucid Motors'),       1, 'https://boards.greenhouse.io/lucidmotors',        1),
((SELECT id FROM company WHERE name = 'SpaceX'),             1, 'https://boards.greenhouse.io/spacex',             1),
((SELECT id FROM company WHERE name = 'Palantir'),           1, 'https://boards.greenhouse.io/palantir',           1),
((SELECT id FROM company WHERE name = 'Squarespace'),        1, 'https://boards.greenhouse.io/squarespace',        1),
((SELECT id FROM company WHERE name = 'Webflow'),            1, 'https://boards.greenhouse.io/webflow',            1),
((SELECT id FROM company WHERE name = 'Calendly'),           1, 'https://boards.greenhouse.io/calendly',           1),
((SELECT id FROM company WHERE name = 'ClickUp'),            1, 'https://boards.greenhouse.io/clickup',            1),
((SELECT id FROM company WHERE name = 'Monday.com'),         1, 'https://boards.greenhouse.io/mondaydotcom',       1),
((SELECT id FROM company WHERE name = 'Miro'),               1, 'https://boards.greenhouse.io/miro',               1),
((SELECT id FROM company WHERE name = 'Loom'),               1, 'https://boards.greenhouse.io/loom',               1),
((SELECT id FROM company WHERE name = 'Aircall'),            1, 'https://boards.greenhouse.io/aircall',            1),
((SELECT id FROM company WHERE name = 'Dialpad'),            1, 'https://boards.greenhouse.io/dialpad',            1),
((SELECT id FROM company WHERE name = 'RingCentral'),        1, 'https://boards.greenhouse.io/ringcentral',        1),
((SELECT id FROM company WHERE name = 'Talkdesk'),           1, 'https://boards.greenhouse.io/talkdesk',           1),
((SELECT id FROM company WHERE name = 'Five9'),              1, 'https://boards.greenhouse.io/five9',              1),
((SELECT id FROM company WHERE name = 'Genesys'),            1, 'https://boards.greenhouse.io/genesys',            1);


-- SMARTRECRUITERS mappings
INSERT IGNORE INTO company_ats (company_id, ats_platform_id, ats_job_url, active) VALUES
((SELECT id FROM company WHERE name = 'Infosys'),             2, 'https://careers.smartrecruiters.com/Infosys',             1),
((SELECT id FROM company WHERE name = 'Wipro'),               2, 'https://careers.smartrecruiters.com/Wipro',               1),
((SELECT id FROM company WHERE name = 'HCL Technologies'),    2, 'https://careers.smartrecruiters.com/HCLTechnologies',      1),
((SELECT id FROM company WHERE name = 'Tech Mahindra'),       2, 'https://careers.smartrecruiters.com/TechMahindra',         1),
((SELECT id FROM company WHERE name = 'Mphasis'),             2, 'https://careers.smartrecruiters.com/Mphasis',              1),
((SELECT id FROM company WHERE name = 'Hexaware'),            2, 'https://careers.smartrecruiters.com/Hexaware',             1),
((SELECT id FROM company WHERE name = 'Persistent Systems'),  2, 'https://careers.smartrecruiters.com/PersistentSystems',    1),
((SELECT id FROM company WHERE name = 'Zensar'),              2, 'https://careers.smartrecruiters.com/Zensar',               1),
((SELECT id FROM company WHERE name = 'KPIT Technologies'),   2, 'https://careers.smartrecruiters.com/KPITTechnologies',     1),
((SELECT id FROM company WHERE name = 'Cyient'),              2, 'https://careers.smartrecruiters.com/Cyient',               1),
((SELECT id FROM company WHERE name = 'Mastek'),              2, 'https://careers.smartrecruiters.com/Mastek',               1),
((SELECT id FROM company WHERE name = 'Tata Elxsi'),          2, 'https://careers.smartrecruiters.com/TataElxsi',            1),
((SELECT id FROM company WHERE name = 'L&T Technology Services'),2,'https://careers.smartrecruiters.com/LTTechnologyServices',1),
((SELECT id FROM company WHERE name = 'Birlasoft'),           2, 'https://careers.smartrecruiters.com/Birlasoft',            1),
((SELECT id FROM company WHERE name = 'Bosch'),               2, 'https://careers.smartrecruiters.com/BoschGroup',           1),
((SELECT id FROM company WHERE name = 'Visa'),                2, 'https://careers.smartrecruiters.com/Visa',                 1),
((SELECT id FROM company WHERE name = 'IKEA'),                2, 'https://careers.smartrecruiters.com/IKEA',                 1),
((SELECT id FROM company WHERE name = 'Volvo Group'),         2, 'https://careers.smartrecruiters.com/VolvoGroup',           1),
((SELECT id FROM company WHERE name = 'Nokia'),               2, 'https://careers.smartrecruiters.com/Nokia',                1),
((SELECT id FROM company WHERE name = 'Philips'),             2, 'https://careers.smartrecruiters.com/Philips',              1),
((SELECT id FROM company WHERE name = 'Publicis Groupe'),     2, 'https://careers.smartrecruiters.com/PublicisGroupe',       1),
((SELECT id FROM company WHERE name = 'Capgemini'),           2, 'https://careers.smartrecruiters.com/Capgemini',            1),
((SELECT id FROM company WHERE name = 'Vestas'),              2, 'https://careers.smartrecruiters.com/Vestas',               1),
((SELECT id FROM company WHERE name = 'LVMH'),                2, 'https://careers.smartrecruiters.com/LVMH',                 1),
((SELECT id FROM company WHERE name = 'Hilti'),               2, 'https://careers.smartrecruiters.com/Hilti',                1),
((SELECT id FROM company WHERE name = 'Takeda'),              2, 'https://careers.smartrecruiters.com/Takeda',               1),
((SELECT id FROM company WHERE name = 'Swarovski'),           2, 'https://careers.smartrecruiters.com/Swarovski',            1),
((SELECT id FROM company WHERE name = 'Axa'),                 2, 'https://careers.smartrecruiters.com/Axa',                  1),
((SELECT id FROM company WHERE name = 'TotalEnergies'),       2, 'https://careers.smartrecruiters.com/TotalEnergies',        1),
((SELECT id FROM company WHERE name = 'Veolia'),              2, 'https://careers.smartrecruiters.com/Veolia',               1),
((SELECT id FROM company WHERE name = 'Danone'),              2, 'https://careers.smartrecruiters.com/Danone',               1),
((SELECT id FROM company WHERE name = 'Schneider Electric'),  2, 'https://careers.smartrecruiters.com/SchneiderElectric',    1),
((SELECT id FROM company WHERE name = 'Air Liquide'),         2, 'https://careers.smartrecruiters.com/AirLiquide',           1),
((SELECT id FROM company WHERE name = 'Siemens Mobility'),    2, 'https://careers.smartrecruiters.com/SiemensMobility',      1),
((SELECT id FROM company WHERE name = 'BNP Paribas'),         2, 'https://careers.smartrecruiters.com/BNPParibas',           1),
((SELECT id FROM company WHERE name = 'Sodexo'),              2, 'https://careers.smartrecruiters.com/Sodexo',               1),
((SELECT id FROM company WHERE name = 'Dassault Systemes'),   2, 'https://careers.smartrecruiters.com/DassaultSystemes',     1),
((SELECT id FROM company WHERE name = 'Orange'),              2, 'https://careers.smartrecruiters.com/Orange',               1),
((SELECT id FROM company WHERE name = 'Allianz'),             2, 'https://careers.smartrecruiters.com/Allianz',              1),
((SELECT id FROM company WHERE name = 'Thales'),              2, 'https://careers.smartrecruiters.com/Thales',               1),
((SELECT id FROM company WHERE name = 'Alstom'),              2, 'https://careers.smartrecruiters.com/Alstom',               1),
((SELECT id FROM company WHERE name = 'Accor'),               2, 'https://careers.smartrecruiters.com/Accor',                1),
((SELECT id FROM company WHERE name = 'Sanofi'),              2, 'https://careers.smartrecruiters.com/Sanofi',               1),
((SELECT id FROM company WHERE name = 'Renault'),             2, 'https://careers.smartrecruiters.com/Renault',              1),
((SELECT id FROM company WHERE name = 'Valeo'),               2, 'https://careers.smartrecruiters.com/Valeo',                1),
((SELECT id FROM company WHERE name = 'Michelin'),            2, 'https://careers.smartrecruiters.com/Michelin',             1),
((SELECT id FROM company WHERE name = 'EDF'),                 2, 'https://careers.smartrecruiters.com/EDF',                  1),
((SELECT id FROM company WHERE name = 'Engie'),               2, 'https://careers.smartrecruiters.com/Engie',                1),
((SELECT id FROM company WHERE name = 'Heineken'),            2, 'https://careers.smartrecruiters.com/Heineken',             1),
((SELECT id FROM company WHERE name = 'Carlsberg'),           2, 'https://careers.smartrecruiters.com/Carlsberg',            1),
((SELECT id FROM company WHERE name = 'ABB'),                 2, 'https://careers.smartrecruiters.com/ABB',                  1),
((SELECT id FROM company WHERE name = 'Siemens'),             2, 'https://careers.smartrecruiters.com/Siemens',              1),
((SELECT id FROM company WHERE name = 'Honeywell'),           2, 'https://careers.smartrecruiters.com/Honeywell',            1),
((SELECT id FROM company WHERE name = 'Ericsson'),            2, 'https://careers.smartrecruiters.com/Ericsson',             1),
((SELECT id FROM company WHERE name = 'Deutsche Telekom'),    2, 'https://careers.smartrecruiters.com/DeutscheTelekom',      1),
((SELECT id FROM company WHERE name = 'Vodafone'),            2, 'https://careers.smartrecruiters.com/Vodafone',             1),
((SELECT id FROM company WHERE name = 'Teleperformance'),     2, 'https://careers.smartrecruiters.com/Teleperformance',      1),
((SELECT id FROM company WHERE name = 'Concentrix'),          2, 'https://careers.smartrecruiters.com/Concentrix',           1),
((SELECT id FROM company WHERE name = 'WNS'),                 2, 'https://careers.smartrecruiters.com/WNS',                  1),
((SELECT id FROM company WHERE name = 'EXL Service'),         2, 'https://careers.smartrecruiters.com/EXLService',           1),
((SELECT id FROM company WHERE name = 'Genpact'),             2, 'https://careers.smartrecruiters.com/Genpact',              1),
((SELECT id FROM company WHERE name = 'Amdocs'),              2, 'https://careers.smartrecruiters.com/Amdocs',               1),
((SELECT id FROM company WHERE name = 'Fujitsu'),             2, 'https://careers.smartrecruiters.com/Fujitsu',              1),
((SELECT id FROM company WHERE name = 'NTT Data'),            2, 'https://careers.smartrecruiters.com/NTTData',              1),
((SELECT id FROM company WHERE name = 'Hitachi'),             2, 'https://careers.smartrecruiters.com/Hitachi',              1),
((SELECT id FROM company WHERE name = 'NEC'),                 2, 'https://careers.smartrecruiters.com/NEC',                  1),
((SELECT id FROM company WHERE name = 'Tata Communications'), 2, 'https://careers.smartrecruiters.com/TataCommunications',   1),
((SELECT id FROM company WHERE name = 'Sterlite Tech'),       2, 'https://careers.smartrecruiters.com/SterliteTech',         1);

