-- ============================================================
-- JobRadar Company Seed Data - Part 3
-- Global SaaS, Semiconductor, Consulting, Media & More
-- ============================================================

USE job_radar;

INSERT IGNORE INTO company (name, industry, active) VALUES

-- Global SaaS - Project & Collaboration
('Basecamp',                'Productivity',     1),
('Trello',                  'Productivity',     1),
('Jira',                    'Productivity',     1),
('Confluence',              'Productivity',     1),
('Smartsheet',              'Productivity',     1),
('Wrike',                   'Productivity',     1),
('Teamwork',                'Productivity',     1),
('Podio',                   'Productivity',     1),
('Zoho Projects',           'Productivity',     1),
('ProofHub',                'Productivity',     1),
('Hive',                    'Productivity',     1),
('Nifty',                   'Productivity',     1),
('Height',                  'Productivity',     1),
('Plane',                   'Productivity',     1),
('Shortcut',                'Productivity',     1),
('Clubhouse',               'Productivity',     1),
('YouTrack',                'Productivity',     1),
('Backlog',                 'Productivity',     1),
('Targetprocess',           'Productivity',     1),
('LeanKit',                 'Productivity',     1),

-- Document & Knowledge Management
('Guru',                    'Productivity',     1),
('Tettra',                  'Productivity',     1),
('Nuclino',                 'Productivity',     1),
('Slite',                   'Productivity',     1),
('Slab',                    'Productivity',     1),
('Outline',                 'Productivity',     1),
('BookStack',               'Productivity',     1),
('Helpjuice',               'Productivity',     1),
('Document360',             'Productivity',     1),
('GitBook',                 'Productivity',     1),
('Confluence Cloud',        'Productivity',     1),
('Zendesk Guide',           'Customer Success', 1),
('Freshdesk KMS',           'Customer Success', 1),
('HelpScout',               'Customer Success', 1),
('Groove',                  'Customer Success', 1),
('Kayako',                  'Customer Success', 1),
('Re:amaze',                'Customer Success', 1),
('Crisp',                   'Customer Success', 1),
('Tidio',                   'Customer Success', 1),
('LiveChat',                'Customer Success', 1),

-- Data & Analytics
('Tableau',                 'Analytics',        1),
('Power BI',                'Analytics',        1),
('Qlik',                    'Analytics',        1),
('Microstrategy',           'Analytics',        1),
('TIBCO',                   'Analytics',        1),
('Information Builders',    'Analytics',        1),
('Yellowfin',               'Analytics',        1),
('Sisense',                 'Analytics',        1),
('Zoho Analytics',          'Analytics',        1),
('GoodData',                'Analytics',        1),
('Logi Analytics',          'Analytics',        1),
('Domo',                    'Analytics',        1),
('Klipfolio',               'Analytics',        1),
('Geckoboard',              'Analytics',        1),
('Databox',                 'Analytics',        1),
('Whatagraph',              'Analytics',        1),
('Cyfe',                    'Analytics',        1),
('AgencyAnalytics',         'Analytics',        1),
('Supermetrics',            'Analytics',        1),
('Funnel.io',               'Analytics',        1),

-- Data Engineering & Pipelines
('Informatica',             'Data',             1),
('Talend',                  'Data',             1),
('MuleSoft',                'Integration',      1),
('Dell Boomi',              'Integration',      1),
('SnapLogic',               'Integration',      1),
('Jitterbit',               'Integration',      1),
('Celigo',                  'Integration',      1),
('Tray.io',                 'Integration',      1),
('Cyclr',                   'Integration',      1),
('Alumio',                  'Integration',      1),
('Stitch Data',             'Data',             1),
('Xplenty',                 'Data',             1),
('Hevo Data',               'Data',             1),
('RudderStack',             'Data',             1),
('Census',                  'Data',             1),
('Hightouch',               'Data',             1),
('Polytomic',               'Data',             1),
('Grouparoo',               'Data',             1),
('Omnata',                  'Data',             1),
('Profilesync',             'Data',             1),

-- Cybersecurity
('Malwarebytes',            'Security',         1),
('Webroot',                 'Security',         1),
('Carbon Black',            'Security',         1),
('McAfee',                  'Security',         1),
('Symantec',                'Security',         1),
('Trend Micro',             'Security',         1),
('Kaspersky',               'Security',         1),
('ESET',                    'Security',         1),
('Avast',                   'Security',         1),
('Bitdefender',             'Security',         1),
('Sophos',                  'Security',         1),
('Check Point',             'Security',         1),
('WatchGuard',              'Security',         1),
('Barracuda Networks',      'Security',         1),
('Proofpoint',              'Security',         1),
('Mimecast',                'Security',         1),
('Egress',                  'Security',         1),
('Tessian',                 'Security',         1),
('Abnormal Security',       'Security',         1),
('Cofense',                 'Security',         1),
('KnowBe4',                 'Security',         1),
('Proofpoint India',        'Security',         1),
('Secureworks',             'Security',         1),
('Trustwave',               'Security',         1),
('Arctic Wolf',             'Security',         1),
('Expel',                   'Security',         1),
('Huntress',                'Security',         1),
('Red Canary',              'Security',         1),
('Cybereason',              'Security',         1),
('Deep Instinct',           'Security',         1),

-- Semiconductor & Hardware
('Texas Instruments India', 'Semiconductors',   1),
('STMicroelectronics',      'Semiconductors',   1),
('NXP Semiconductors',      'Semiconductors',   1),
('Infineon Technologies',   'Semiconductors',   1),
('Renesas Electronics',     'Semiconductors',   1),
('Microchip',               'Semiconductors',   1),
('Silicon Labs',            'Semiconductors',   1),
('Lattice Semiconductor',   'Semiconductors',   1),
('Xilinx',                  'Semiconductors',   1),
('Altera',                  'Semiconductors',   1),
('Arm',                     'Semiconductors',   1),
('RISC-V International',    'Semiconductors',   1),
('SiFive',                  'Semiconductors',   1),
('Esperanto Technologies',  'Semiconductors',   1),
('Tenstorrent',             'Semiconductors',   1),
('Graphcore',               'Semiconductors',   1),
('Cerebras',                'Semiconductors',   1),
('Groq',                    'Semiconductors',   1),
('Sambanova',               'Semiconductors',   1),
('d-Matrix',                'Semiconductors',   1),

-- Telecom
('Jio',                     'Telecom',          1),
('Airtel',                  'Telecom',          1),
('BSNL',                    'Telecom',          1),
('Vi',                      'Telecom',          1),
('MTNL',                    'Telecom',          1),
('Dish TV',                 'Telecom',          1),
('Tata Sky',                'Telecom',          1),
('ACT Fibernet',            'Telecom',          1),
('Hathway',                 'Telecom',          1),
('SIFY Technologies',       'Telecom',          1),
('Netmagic',                'Cloud',            1),
('CtrlS',                   'Cloud',            1),
('Yotta',                   'Cloud',            1),
('NxtGen',                  'Cloud',            1),
('Web Werks',               'Cloud',            1),
('Colt Technology',         'Telecom',          1),
('Zayo',                    'Telecom',          1),
('Cogent',                  'Telecom',          1),
('Lumen Technologies',      'Telecom',          1),
('GTT Communications',      'Telecom',          1),

-- Healthcare & Pharma Tech
('Meditech',                'Health Tech',      1),
('Epic Systems',            'Health Tech',      1),
('Cerner',                  'Health Tech',      1),
('Allscripts',              'Health Tech',      1),
('athenahealth',            'Health Tech',      1),
('eClinicalWorks',          'Health Tech',      1),
('NextGen Healthcare',      'Health Tech',      1),
('GE Healthcare',           'Health Tech',      1),
('Philips Healthcare',      'Health Tech',      1),
('Siemens Healthineers',    'Health Tech',      1),
('Medtronic',               'Health Tech',      1),
('Abbott',                  'Health Tech',      1),
('BD',                      'Health Tech',      1),
('Zimmer Biomet',           'Health Tech',      1),
('Stryker',                 'Health Tech',      1),
('Boston Scientific',       'Health Tech',      1),
('Edwards Lifesciences',    'Health Tech',      1),
('Integra LifeSciences',    'Health Tech',      1),
('NovaBay Pharmaceuticals', 'Health Tech',      1),
('Masimo',                  'Health Tech',      1),
('Natus Medical',           'Health Tech',      1),
('Haemonetics',             'Health Tech',      1),
('Nuvax',                   'Health Tech',      1),
('Align Technology',        'Health Tech',      1),
('iRhythm',                 'Health Tech',      1),

-- Biotech & Pharma
('AstraZeneca',             'Pharma',           1),
('Novartis',                'Pharma',           1),
('Roche',                   'Pharma',           1),
('Pfizer',                  'Pharma',           1),
('Johnson & Johnson',       'Pharma',           1),
('Merck',                   'Pharma',           1),
('Eli Lilly',               'Pharma',           1),
('AbbVie',                  'Pharma',           1),
('Amgen',                   'Pharma',           1),
('Gilead Sciences',         'Pharma',           1),
('Biogen',                  'Pharma',           1),
('Regeneron',               'Pharma',           1),
('Moderna',                 'Pharma',           1),
('BioNTech',                'Pharma',           1),
('Genentech',               'Pharma',           1),
('Illumina',                'Pharma',           1),
('10x Genomics',            'Pharma',           1),
('Pacific Biosciences',     'Pharma',           1),
('Twist Bioscience',        'Pharma',           1),
('Recursion Pharma',        'Pharma',           1),
('Sun Pharma',              'Pharma',           1),
('Dr. Reddys',              'Pharma',           1),
('Cipla',                   'Pharma',           1),
('Lupin',                   'Pharma',           1),
('Biocon',                  'Pharma',           1),
('Wockhardt',               'Pharma',           1),
('Aurobindo Pharma',        'Pharma',           1),
('Gland Pharma',            'Pharma',           1),
('Divis Laboratories',      'Pharma',           1),
('Torrent Pharma',          'Pharma',           1),

-- Travel & Hospitality Tech
('MakeMyTrip',              'Travel',           1),
('Cleartrip',               'Travel',           1),
('Yatra',                   'Travel',           1),
('Goibibo',                 'Travel',           1),
('Ixigo',                   'Travel',           1),
('EaseMyTrip',              'Travel',           1),
('Booking Holdings',        'Travel',           1),
('Expedia Group',           'Travel',           1),
('Tripadvisor',             'Travel',           1),
('Skyscanner',              'Travel',           1),
('Kayak',                   'Travel',           1),
('Hopper',                  'Travel',           1),
('Airhelp',                 'Travel',           1),
('TravelPerk',              'Travel',           1),
('TripActions',             'Travel',           1),
('Navan',                   'Travel',           1),
('Concur',                  'Travel',           1),
('Egencia',                 'Travel',           1),
('BCD Travel',              'Travel',           1),
('FCM Travel',              'Travel',           1),

-- EdTech Global
('Chegg',                   'EdTech',           1),
('Khan Academy',            'EdTech',           1),
('Pluralsight',             'EdTech',           1),
('LinkedIn Learning',       'EdTech',           1),
('Skillshare',              'EdTech',           1),
('MasterClass',             'EdTech',           1),
('Brilliant',               'EdTech',           1),
('Codecademy',              'EdTech',           1),
('Treehouse',               'EdTech',           1),
('Pluralsight Skills',      'EdTech',           1),
('O Reilly',                'EdTech',           1),
('Safari Books',            'EdTech',           1),
('Packt',                   'EdTech',           1),
('Manning',                 'EdTech',           1),
('Apress',                  'EdTech',           1),
('Frontend Masters',        'EdTech',           1),
('Egghead',                 'EdTech',           1),
('TestDome',                'EdTech',           1),
('HackerRank',              'EdTech',           1),
('LeetCode',                'EdTech',           1),
('CodeSignal',              'EdTech',           1),
('Codility',                'EdTech',           1),
('iMocha',                  'EdTech',           1),
('HackerEarth',             'EdTech',           1),
('Talview',                 'EdTech',           1),
('Mettl',                   'EdTech',           1),
('Mercer Mettl',            'EdTech',           1),
('Hirepro',                 'EdTech',           1),
('Xobin',                   'EdTech',           1),
('Adaface',                 'EdTech',           1),

-- Media & Content
('Times Internet',          'Media',            1),
('Network18',               'Media',            1),
('NDTV',                    'Media',            1),
('India Today Group',       'Media',            1),
('HT Media',                'Media',            1),
('Dainik Bhaskar',          'Media',            1),
('Jagran Prakashan',        'Media',            1),
('Zee Entertainment',       'Media',            1),
('Sun TV Network',          'Media',            1),
('TV18',                    'Media',            1),
('Quint Digital',           'Media',            1),
('The Wire',                'Media',            1),
('Scroll Media',            'Media',            1),
('ThePrint',                'Media',            1),
('Newslaundry',             'Media',            1);


-- ============================================================
-- GREENHOUSE MAPPINGS (Part 3)
-- ============================================================

INSERT IGNORE INTO company_ats (company_id, ats_platform_id, ats_job_url, active) VALUES
((SELECT id FROM company WHERE name = 'Smartsheet'),            1, 'https://boards.greenhouse.io/smartsheet',            1),
((SELECT id FROM company WHERE name = 'Wrike'),                 1, 'https://boards.greenhouse.io/wrike',                  1),
((SELECT id FROM company WHERE name = 'Domo'),                  1, 'https://boards.greenhouse.io/domo',                   1),
((SELECT id FROM company WHERE name = 'Tableau'),               1, 'https://boards.greenhouse.io/tableau',                1),
((SELECT id FROM company WHERE name = 'Qlik'),                  1, 'https://boards.greenhouse.io/qlik',                   1),
((SELECT id FROM company WHERE name = 'Sisense'),               1, 'https://boards.greenhouse.io/sisense',                1),
((SELECT id FROM company WHERE name = 'Informatica'),           1, 'https://boards.greenhouse.io/informatica',            1),
((SELECT id FROM company WHERE name = 'Talend'),                1, 'https://boards.greenhouse.io/talend',                 1),
((SELECT id FROM company WHERE name = 'SnapLogic'),             1, 'https://boards.greenhouse.io/snaplogic',              1),
((SELECT id FROM company WHERE name = 'Jitterbit'),             1, 'https://boards.greenhouse.io/jitterbit',              1),
((SELECT id FROM company WHERE name = 'Celigo'),                1, 'https://boards.greenhouse.io/celigo',                 1),
((SELECT id FROM company WHERE name = 'Hevo Data'),             1, 'https://boards.greenhouse.io/hevodata',               1),
((SELECT id FROM company WHERE name = 'RudderStack'),           1, 'https://boards.greenhouse.io/rudderstack',            1),
((SELECT id FROM company WHERE name = 'Census'),                1, 'https://boards.greenhouse.io/census',                 1),
((SELECT id FROM company WHERE name = 'Hightouch'),             1, 'https://boards.greenhouse.io/hightouch',              1),
((SELECT id FROM company WHERE name = 'Carbon Black'),          1, 'https://boards.greenhouse.io/carbonblack',            1),
((SELECT id FROM company WHERE name = 'Proofpoint'),            1, 'https://boards.greenhouse.io/proofpoint',             1),
((SELECT id FROM company WHERE name = 'Mimecast'),              1, 'https://boards.greenhouse.io/mimecast',               1),
((SELECT id FROM company WHERE name = 'Tessian'),               1, 'https://boards.greenhouse.io/tessian',                1),
((SELECT id FROM company WHERE name = 'KnowBe4'),               1, 'https://boards.greenhouse.io/knowbe4',                1),
((SELECT id FROM company WHERE name = 'Secureworks'),           1, 'https://boards.greenhouse.io/secureworks',            1),
((SELECT id FROM company WHERE name = 'Arctic Wolf'),           1, 'https://boards.greenhouse.io/arcticwolf',             1),
((SELECT id FROM company WHERE name = 'Expel'),                 1, 'https://boards.greenhouse.io/expel',                  1),
((SELECT id FROM company WHERE name = 'Red Canary'),            1, 'https://boards.greenhouse.io/redcanary',              1),
((SELECT id FROM company WHERE name = 'Cybereason'),            1, 'https://boards.greenhouse.io/cybereason',             1),
((SELECT id FROM company WHERE name = 'Deep Instinct'),         1, 'https://boards.greenhouse.io/deepinstinct',           1),
((SELECT id FROM company WHERE name = 'Arm'),                   1, 'https://boards.greenhouse.io/arm',                    1),
((SELECT id FROM company WHERE name = 'SiFive'),                1, 'https://boards.greenhouse.io/sifive',                 1),
((SELECT id FROM company WHERE name = 'Tenstorrent'),           1, 'https://boards.greenhouse.io/tenstorrent',            1),
((SELECT id FROM company WHERE name = 'Graphcore'),             1, 'https://boards.greenhouse.io/graphcore',              1),
((SELECT id FROM company WHERE name = 'Cerebras'),              1, 'https://boards.greenhouse.io/cerebras',               1),
((SELECT id FROM company WHERE name = 'Groq'),                  1, 'https://boards.greenhouse.io/groq',                   1),
((SELECT id FROM company WHERE name = 'Sambanova'),             1, 'https://boards.greenhouse.io/sambanova',              1),
((SELECT id FROM company WHERE name = 'MakeMyTrip'),            1, 'https://boards.greenhouse.io/makemytrip',             1),
((SELECT id FROM company WHERE name = 'Cleartrip'),             1, 'https://boards.greenhouse.io/cleartrip',              1),
((SELECT id FROM company WHERE name = 'Ixigo'),                 1, 'https://boards.greenhouse.io/ixigo',                  1),
((SELECT id FROM company WHERE name = 'EaseMyTrip'),            1, 'https://boards.greenhouse.io/easemytrip',             1),
((SELECT id FROM company WHERE name = 'TravelPerk'),            1, 'https://boards.greenhouse.io/travelperk',             1),
((SELECT id FROM company WHERE name = 'TripActions'),           1, 'https://boards.greenhouse.io/tripactions',            1),
((SELECT id FROM company WHERE name = 'Navan'),                 1, 'https://boards.greenhouse.io/navan',                  1),
((SELECT id FROM company WHERE name = 'Hopper'),                1, 'https://boards.greenhouse.io/hopper',                 1),
((SELECT id FROM company WHERE name = 'Skyscanner'),            1, 'https://boards.greenhouse.io/skyscanner',             1),
((SELECT id FROM company WHERE name = 'Tripadvisor'),           1, 'https://boards.greenhouse.io/tripadvisor',            1),
((SELECT id FROM company WHERE name = 'Pluralsight'),           1, 'https://boards.greenhouse.io/pluralsight',            1),
((SELECT id FROM company WHERE name = 'Skillshare'),            1, 'https://boards.greenhouse.io/skillshare',             1),
((SELECT id FROM company WHERE name = 'MasterClass'),           1, 'https://boards.greenhouse.io/masterclass',            1),
((SELECT id FROM company WHERE name = 'Brilliant'),             1, 'https://boards.greenhouse.io/brilliant',              1),
((SELECT id FROM company WHERE name = 'Codecademy'),            1, 'https://boards.greenhouse.io/codecademy',             1),
((SELECT id FROM company WHERE name = 'HackerRank'),            1, 'https://boards.greenhouse.io/hackerrank',             1),
((SELECT id FROM company WHERE name = 'CodeSignal'),            1, 'https://boards.greenhouse.io/codesignal',             1),
((SELECT id FROM company WHERE name = 'HackerEarth'),           1, 'https://boards.greenhouse.io/hackerearth',            1),
((SELECT id FROM company WHERE name = 'Benchling'),             1, 'https://boards.greenhouse.io/benchling',              1),
((SELECT id FROM company WHERE name = 'Illumina'),              1, 'https://boards.greenhouse.io/illumina',               1),
((SELECT id FROM company WHERE name = '10x Genomics'),          1, 'https://boards.greenhouse.io/10xgenomics',            1),
((SELECT id FROM company WHERE name = 'Recursion Pharma'),      1, 'https://boards.greenhouse.io/recursionpharma',        1),
((SELECT id FROM company WHERE name = 'Moderna'),               1, 'https://boards.greenhouse.io/modernatx',              1),
((SELECT id FROM company WHERE name = 'Genentech'),             1, 'https://boards.greenhouse.io/genentech',              1),
((SELECT id FROM company WHERE name = 'Gilead Sciences'),       1, 'https://boards.greenhouse.io/gilead',                 1),
((SELECT id FROM company WHERE name = 'Biogen'),                1, 'https://boards.greenhouse.io/biogen',                 1),
((SELECT id FROM company WHERE name = 'Regeneron'),             1, 'https://boards.greenhouse.io/regeneron',              1),
((SELECT id FROM company WHERE name = 'Amgen'),                 1, 'https://boards.greenhouse.io/amgen',                  1),
((SELECT id FROM company WHERE name = 'athenahealth'),          1, 'https://boards.greenhouse.io/athenahealth',           1),
((SELECT id FROM company WHERE name = 'iRhythm'),               1, 'https://boards.greenhouse.io/irhythm',                1),
((SELECT id FROM company WHERE name = 'Masimo'),                1, 'https://boards.greenhouse.io/masimo',                 1),
((SELECT id FROM company WHERE name = 'Innovaccer'),            1, 'https://boards.greenhouse.io/innovaccer',             1),
((SELECT id FROM company WHERE name = 'Flatiron Health'),       1, 'https://boards.greenhouse.io/flatironhealth',         1),
((SELECT id FROM company WHERE name = 'Times Internet'),        1, 'https://boards.greenhouse.io/timesinternet',          1),
((SELECT id FROM company WHERE name = 'Colt Technology'),       1, 'https://boards.greenhouse.io/colt',                   1),
((SELECT id FROM company WHERE name = 'Lumen Technologies'),    1, 'https://boards.greenhouse.io/lumen',                  1),
((SELECT id FROM company WHERE name = 'Jio'),                   1, 'https://boards.greenhouse.io/jio',                    1),
((SELECT id FROM company WHERE name = 'Airtel'),                1, 'https://boards.greenhouse.io/airtel',                 1);


-- ============================================================
-- SMARTRECRUITERS MAPPINGS (Part 3)
-- ============================================================

INSERT IGNORE INTO company_ats (company_id, ats_platform_id, ats_job_url, active) VALUES
((SELECT id FROM company WHERE name = 'Smartsheet'),            2, 'https://careers.smartrecruiters.com/Smartsheet',            1),
((SELECT id FROM company WHERE name = 'Tableau'),               2, 'https://careers.smartrecruiters.com/Tableau',               1),
((SELECT id FROM company WHERE name = 'TIBCO'),                 2, 'https://careers.smartrecruiters.com/TIBCO',                  1),
((SELECT id FROM company WHERE name = 'Informatica'),           2, 'https://careers.smartrecruiters.com/Informatica',            1),
((SELECT id FROM company WHERE name = 'Talend'),                2, 'https://careers.smartrecruiters.com/Talend',                 1),
((SELECT id FROM company WHERE name = 'MuleSoft'),              2, 'https://careers.smartrecruiters.com/MuleSoft',               1),
((SELECT id FROM company WHERE name = 'Dell Boomi'),            2, 'https://careers.smartrecruiters.com/DellBoomi',              1),
((SELECT id FROM company WHERE name = 'Proofpoint'),            2, 'https://careers.smartrecruiters.com/Proofpoint',             1),
((SELECT id FROM company WHERE name = 'Mimecast'),              2, 'https://careers.smartrecruiters.com/Mimecast',               1),
((SELECT id FROM company WHERE name = 'Sophos'),                2, 'https://careers.smartrecruiters.com/Sophos',                 1),
((SELECT id FROM company WHERE name = 'Check Point'),           2, 'https://careers.smartrecruiters.com/CheckPoint',             1),
((SELECT id FROM company WHERE name = 'Barracuda Networks'),    2, 'https://careers.smartrecruiters.com/BarracudaNetworks',      1),
((SELECT id FROM company WHERE name = 'Trend Micro'),           2, 'https://careers.smartrecruiters.com/TrendMicro',             1),
((SELECT id FROM company WHERE name = 'Kaspersky'),             2, 'https://careers.smartrecruiters.com/Kaspersky',              1),
((SELECT id FROM company WHERE name = 'Bitdefender'),           2, 'https://careers.smartrecruiters.com/Bitdefender',            1),
((SELECT id FROM company WHERE name = 'STMicroelectronics'),    2, 'https://careers.smartrecruiters.com/STMicroelectronics',     1),
((SELECT id FROM company WHERE name = 'NXP Semiconductors'),    2, 'https://careers.smartrecruiters.com/NXPSemiconductors',      1),
((SELECT id FROM company WHERE name = 'Infineon Technologies'), 2, 'https://careers.smartrecruiters.com/InfineonTechnologies',   1),
((SELECT id FROM company WHERE name = 'Renesas Electronics'),   2, 'https://careers.smartrecruiters.com/RenesasElectronics',     1),
((SELECT id FROM company WHERE name = 'Silicon Labs'),          2, 'https://careers.smartrecruiters.com/SiliconLabs',            1),
((SELECT id FROM company WHERE name = 'AstraZeneca'),           2, 'https://careers.smartrecruiters.com/AstraZeneca',            1),
((SELECT id FROM company WHERE name = 'Novartis'),              2, 'https://careers.smartrecruiters.com/Novartis',               1),
((SELECT id FROM company WHERE name = 'Roche'),                 2, 'https://careers.smartrecruiters.com/Roche',                  1),
((SELECT id FROM company WHERE name = 'Pfizer'),                2, 'https://careers.smartrecruiters.com/Pfizer',                 1),
((SELECT id FROM company WHERE name = 'Johnson & Johnson'),     2, 'https://careers.smartrecruiters.com/JohnsonJohnson',         1),
((SELECT id FROM company WHERE name = 'Merck'),                 2, 'https://careers.smartrecruiters.com/Merck',                  1),
((SELECT id FROM company WHERE name = 'Sanofi'),                2, 'https://careers.smartrecruiters.com/Sanofi',                 1),
((SELECT id FROM company WHERE name = 'Sun Pharma'),            2, 'https://careers.smartrecruiters.com/SunPharma',              1),
((SELECT id FROM company WHERE name = 'Cipla'),                 2, 'https://careers.smartrecruiters.com/Cipla',                  1),
((SELECT id FROM company WHERE name = 'Lupin'),                 2, 'https://careers.smartrecruiters.com/Lupin',                  1),
((SELECT id FROM company WHERE name = 'Biocon'),                2, 'https://careers.smartrecruiters.com/Biocon',                 1),
((SELECT id FROM company WHERE name = 'Aurobindo Pharma'),      2, 'https://careers.smartrecruiters.com/AurobindoPharma',        1),
((SELECT id FROM company WHERE name = 'Torrent Pharma'),        2, 'https://careers.smartrecruiters.com/TorrentPharma',          1),
((SELECT id FROM company WHERE name = 'GE Healthcare'),         2, 'https://careers.smartrecruiters.com/GEHealthcare',           1),
((SELECT id FROM company WHERE name = 'Siemens Healthineers'),  2, 'https://careers.smartrecruiters.com/SiemensHealthineers',    1),
((SELECT id FROM company WHERE name = 'Philips Healthcare'),    2, 'https://careers.smartrecruiters.com/Philips',                1),
((SELECT id FROM company WHERE name = 'Medtronic'),             2, 'https://careers.smartrecruiters.com/Medtronic',              1),
((SELECT id FROM company WHERE name = 'Stryker'),               2, 'https://careers.smartrecruiters.com/Stryker',                1),
((SELECT id FROM company WHERE name = 'Boston Scientific'),     2, 'https://careers.smartrecruiters.com/BostonScientific',       1),
((SELECT id FROM company WHERE name = 'MakeMyTrip'),            2, 'https://careers.smartrecruiters.com/MakeMyTrip',             1),
((SELECT id FROM company WHERE name = 'Tripadvisor'),           2, 'https://careers.smartrecruiters.com/Tripadvisor',            1),
((SELECT id FROM company WHERE name = 'Expedia Group'),         2, 'https://careers.smartrecruiters.com/ExpediaGroup',           1),
((SELECT id FROM company WHERE name = 'BCD Travel'),            2, 'https://careers.smartrecruiters.com/BCDTravel',              1),
((SELECT id FROM company WHERE name = 'Booking Holdings'),      2, 'https://careers.smartrecruiters.com/BookingHoldings',        1),
((SELECT id FROM company WHERE name = 'HackerRank'),            2, 'https://careers.smartrecruiters.com/HackerRank',             1),
((SELECT id FROM company WHERE name = 'Pluralsight'),           2, 'https://careers.smartrecruiters.com/Pluralsight',            1),
((SELECT id FROM company WHERE name = 'Chegg'),                 2, 'https://careers.smartrecruiters.com/Chegg',                  1),
((SELECT id FROM company WHERE name = 'Times Internet'),        2, 'https://careers.smartrecruiters.com/TimesInternet',          1),
((SELECT id FROM company WHERE name = 'Zee Entertainment'),     2, 'https://careers.smartrecruiters.com/ZeeEntertainment',       1),
((SELECT id FROM company WHERE name = 'Jio'),                   2, 'https://careers.smartrecruiters.com/Jio',                    1),
((SELECT id FROM company WHERE name = 'Airtel'),                2, 'https://careers.smartrecruiters.com/Airtel',                 1),
((SELECT id FROM company WHERE name = 'Tata Communications'),   2, 'https://careers.smartrecruiters.com/TataCommunications',     1),
((SELECT id FROM company WHERE name = 'Colt Technology'),       2, 'https://careers.smartrecruiters.com/Colt',                   1),
((SELECT id FROM company WHERE name = 'Zayo'),                  2, 'https://careers.smartrecruiters.com/Zayo',                   1),
((SELECT id FROM company WHERE name = 'Lumen Technologies'),    2, 'https://careers.smartrecruiters.com/Lumen',                  1),
((SELECT id FROM company WHERE name = 'Netmagic'),              2, 'https://careers.smartrecruiters.com/Netmagic',               1),
((SELECT id FROM company WHERE name = 'Yotta'),                 2, 'https://careers.smartrecruiters.com/Yotta',                  1),
((SELECT id FROM company WHERE name = 'Domo'),                  2, 'https://careers.smartrecruiters.com/Domo',                   1),
((SELECT id FROM company WHERE name = 'Microstrategy'),         2, 'https://careers.smartrecruiters.com/MicroStrategy',          1),
((SELECT id FROM company WHERE name = 'GoodData'),              2, 'https://careers.smartrecruiters.com/GoodData',               1),
((SELECT id FROM company WHERE name = 'Yellowfin'),             2, 'https://careers.smartrecruiters.com/Yellowfin',              1),
((SELECT id FROM company WHERE name = 'Supermetrics'),          2, 'https://careers.smartrecruiters.com/Supermetrics',           1),
((SELECT id FROM company WHERE name = 'Arm'),                   2, 'https://careers.smartrecruiters.com/Arm',                    1),
((SELECT id FROM company WHERE name = 'Graphcore'),             2, 'https://careers.smartrecruiters.com/Graphcore',              1),
((SELECT id FROM company WHERE name = 'Wrike'),                 2, 'https://careers.smartrecruiters.com/Wrike',                  1),
((SELECT id FROM company WHERE name = 'HelpScout'),             2, 'https://careers.smartrecruiters.com/HelpScout',              1),
((SELECT id FROM company WHERE name = 'LiveChat'),              2, 'https://careers.smartrecruiters.com/LiveChat',               1),
((SELECT id FROM company WHERE name = 'Trustpilot'),            2, 'https://careers.smartrecruiters.com/Trustpilot',             1),
((SELECT id FROM company WHERE name = 'Sprout Social'),         2, 'https://careers.smartrecruiters.com/SproutSocial',           1),
((SELECT id FROM company WHERE name = 'Buffer'),                2, 'https://careers.smartrecruiters.com/Buffer',                 1);

